'use strict';
const RUNTIME='CC8.3.53-PR169-PUBLIC-PUSH-ENTRYPOINT';
const SOURCE='adminkit-pr169-public-push-entrypoint';
const BASE='https://p01--amio-commnets-max--qkpwxnxqqrnw.code.run';
let persistentStoreState=null;
let debugStoreSanitizerState=null;
let postEditorTraceState=null;
let inviteInputGuardState=null;
let inviteLinkPatchState=null;
let privateWarningPatchState=null;
let adCopyLinkPatchState=null;
let adChannelPickerFilterState=null;
let strictAdChannelPickerState=null;
let channelTitleResolverState=null;
let clientAccessBootstrapState=null;
function applyEnv(){process.env.BUILD_VERSION=RUNTIME;process.env.RUNTIME_VERSION=RUNTIME;process.env.BUILD_SOURCE_MARKER=SOURCE;process.env.ADMINKIT_PUBLIC_BASE_URL=BASE;process.env.ADMINKIT_CLEAN_MENU_CORE='1';process.env.ADMINKIT_CLEAN_ENTRYPOINT='1.53.10-pr89-pr169-public-push-entrypoint';process.env.GIT_COMMIT=process.env.GIT_COMMIT||'';process.env.PR165_RUNTIME_WIRED='1';process.env.ADMINKIT_BOT_STARTED_MENU_ENABLED='1';process.env.ADMINKIT_UI_TRACE='1';if(process.env.ADMINKIT_UI_TRACE_LIMIT===undefined)process.env.ADMINKIT_UI_TRACE_LIMIT='120';if(process.env.ADMINKIT_UI_TIMING_LIMIT===undefined)process.env.ADMINKIT_UI_TIMING_LIMIT='120';if(process.env.ADMINKIT_WALKTHROUGH_TRACE_LIMIT===undefined)process.env.ADMINKIT_WALKTHROUGH_TRACE_LIMIT='120';if(process.env.ADMINKIT_BOT_AUDIT_TRACE_LIMIT===undefined)process.env.ADMINKIT_BOT_AUDIT_TRACE_LIMIT='1000';if(process.env.ADMINKIT_STICKERS_ENABLED===undefined)process.env.ADMINKIT_STICKERS_ENABLED='1';if(process.env.ADMINKIT_STICKERS_PACKS===undefined)process.env.ADMINKIT_STICKERS_PACKS='adminkit_whales_v1';}
async function installPersistentStore(){const bootstrap=require('./persistent-store-bootstrap');persistentStoreState=await bootstrap.install({runtimeVersion:RUNTIME});return persistentStoreState;}
function installDebugStoreSanitizer(){const sanitizer=require('./debug-store-sanitizer-pr85');debugStoreSanitizerState=sanitizer.install();return debugStoreSanitizerState;}
function installPostEditorTrace(){const patch=require('./post-editor-walkthrough-trace-patch');postEditorTraceState=patch.install();return postEditorTraceState;}
function installInviteInputGuard(){const patch=require('./ad-invite-input-guard-pr93');inviteInputGuardState=patch.install();return inviteInputGuardState;}
function installInviteLinkPatch(){const patch=require('./stats-campaign-invite-link-patch');inviteLinkPatchState=patch.install();return inviteLinkPatchState;}
function installPrivateWarningPatch(){const patch=require('./stats-campaign-private-warning-patch');privateWarningPatchState=patch.install();return privateWarningPatchState;}
function installAdCopyLinkPatch(){const patch=require('./ad-copy-link-patch-pr94');adCopyLinkPatchState=patch.install();return adCopyLinkPatchState;}
function installAdChannelPickerFilter(){const patch=require('./ad-channel-picker-filter-cc8327');adChannelPickerFilterState=patch.install();return adChannelPickerFilterState;}
function installStrictAdChannelPicker(){const patch=require('./ad-channel-picker-strict-cc8328');strictAdChannelPickerState=patch.install();return strictAdChannelPickerState;}
function installChannelTitleResolver(){const patch=require('./channel-title-resolver-cc8340');channelTitleResolverState=patch.install();return channelTitleResolverState;}
async function installClientAccessRepository(){const access=require('./services/clientAccessService');clientAccessBootstrapState=await access.bootstrap();return clientAccessBootstrapState;}
function installExpressRoutes(){const expressPath=require.resolve('express');const express=require('express');const routes=require('./v3-menu-routes-1539');const performanceRoutes=require('./performance-debug-routes-pr73');const stickerRoutes=require('./stickers-live-routes-pr87');const selftestRoutes=require('./comments-selftest-routes-pr88');const walkthroughRoutes=require('./admin-walkthrough-trace-routes');const campaignRedirectRoutes=require('./ad-campaign-redirect-route-cc8325');const channelTitleRefreshRoutes=require('./channel-title-refresh-routes-cc8342');const channelOwnerBindRoutes=require('./channel-owner-bind-routes-cc8343');if(express&&express.__adminkitClean1539Wrapped)return{ok:true,already:true,runtimeVersion:RUNTIME};function wrappedExpress(){const app=express.apply(this,arguments);routes.install(app);campaignRedirectRoutes.install(app);channelTitleRefreshRoutes.install(app);channelOwnerBindRoutes.install(app);performanceRoutes.install(app);stickerRoutes.install(app);selftestRoutes.install(app);walkthroughRoutes.install(app);return app;}Object.setPrototypeOf(wrappedExpress,express);Object.assign(wrappedExpress,express);wrappedExpress.__adminkitClean1539Wrapped=true;require.cache[expressPath].exports=wrappedExpress;return{ok:true,runtimeVersion:RUNTIME,mode:'express-wrapper-cc8-3-44-auto-tenant-channel-bind',performanceTrace:true,stickersLiveComments:true,commentsSelftest:true,commentsBrowserSelftest:true,commentsMatrixSelftest:true,productionCommentsMatrixProbe:true,commentsTimingTraceV2:true,pr97ReconciledOnCc8344:true,adminWalkthroughTrace:true,botAuditTrace:true,statsMonitoringSelftest:true,statsMonitoringLive:true,statsSourceTracking:true,audienceAttribution:true,campaignLinks:true,adsTopLevel:true,directAdLinks:true,adsChannelPicker:true,adChannelPickerFilter:true,strictAdChannelPicker:true,channelDisplaySanitize:true,globalAdminNameSanitize:true,rejectPersonalNameChannelTitles:true,channelTitleResolver:true,channelTitleRefreshRoute:true,channelOwnerBindRoute:true,tenantChannelBinding:true,autoTenantChannelBind:true,hybridChannelRegistry:true,getChatChannelTitles:true,connectedChannelsWithoutPosts:true,inviteLinksSupported:true,inviteInputGuard:true,adCopyLink:true,adTrackingLinks:true,trackingLinksSupported:true,clckShortLinks:true,clckShortLinksSupported:true,campaignRedirectRoute:'/r/:slug',campaignAttributionSupported:true,campaignSubscriberStats:true,nativeBotStartedMenu:true};}
function installCleanBot(){const botPath=require.resolve('./bot');const legacy=require('./bot');const adapter=require('./clean-bot-campaign-attribution-cc8336');const pushRuntime=require('./clean-bot-live-chat-push-pr165');const clean=pushRuntime.createCleanBot(adapter.createCleanBot(legacy),legacy);require.cache[botPath].exports=clean;return{ok:true,runtimeVersion:RUNTIME,mode:'bot-wrapper-pr165-push-runtime-wired',pushRuntimeVersion:pushRuntime.RUNTIME,pr165LiveChatPushRuntime:true,accessGateEnabled:true,accountSectionReady:true,stickersLiveComments:true,commentsSelftest:true,commentsBrowserSelftest:true,commentsMatrixSelftest:true,productionCommentsMatrixProbe:true,commentsTimingTraceV2:true,pr97ReconciledOnCc8344:true,adminWalkthroughTrace:true,botAuditTrace:true,channelFirstPostPicker:true,nativeStartMenu:true,officialBotStartedMenu:true,buttonDirectLinks:true,activeScreenCleanup:true,giftsActiveScreenCleanup:true,giftsCleanScreens:true,giftsSkipClean:true,ctaUrlReset:true,highlightRoute:true,flowIsolation:true,postsCleanWrapper:true,postsMediaEdit:true,statsCleanUx:true,statsNoTechnicalWording:true,statsWalkthroughTrace:true,statsMonitoringLive:true,statsAttribution:true,statsSourceTracking:true,campaignLinks:true,campaignTextFlow:true,adsTopLevel:true,directAdLinks:true,adsChannelPicker:true,adChannelPickerFilter:true,strictAdChannelPicker:true,channelDisplaySanitize:true,globalAdminNameSanitize:true,rejectPersonalNameChannelTitles:true,channelTitleResolver:true,channelTitleRefreshRoute:true,channelOwnerBindRoute:true,tenantChannelBinding:true,autoTenantChannelBind:true,hybridChannelRegistry:true,getChatChannelTitles:true,connectedChannelsWithoutPosts:true,inviteLinksSupported:true,inviteInputGuard:true,adCopyLink:true,adTrackingLinks:true,trackingLinksSupported:true,clckShortLinks:true,clckShortLinksSupported:true,campaignRedirectRoute:'/r/:slug',campaignAttributionSupported:true,audienceAttribution:true,campaignSubscriberStats:true,archiveCleanUx:true,archiveGrouped:true,archiveWalkthroughTrace:true};}
function info(){const bootstrap=require('./persistent-store-bootstrap');return{ok:true,runtimeVersion:RUNTIME,accessRuntimeVersion:RUNTIME,sourceMarker:SOURCE,entrypoint:'clean-entrypoint-1.53.10-pr89.js',pr165LiveChatPushRuntime:true,menuCanonicalVersion:require('./features/menu-v3/canonical-menu').VERSION,staleEndpointDetected:false,stickersLiveComments:true,commentsSelftest:true,commentsBrowserSelftest:true,commentsMatrixSelftest:true,productionCommentsMatrixProbe:true,commentsTimingTraceV2:true,pr97ReconciledOnCc8344:true,adminWalkthroughTrace:true,botAuditTrace:true,channelFirstPostPicker:true,nativeStartMenu:true,officialBotStartedMenu:true,buttonDirectLinks:true,activeScreenCleanup:true,giftsActiveScreenCleanup:true,giftsCleanScreens:true,giftsSkipClean:true,ctaUrlReset:true,highlightRoute:true,flowIsolation:true,postsCleanWrapper:true,postsMediaEdit:true,statsCleanUx:true,statsNoTechnicalWording:true,statsWalkthroughTrace:true,statsMonitoringLive:true,statsAttribution:true,statsSourceTracking:true,campaignLinks:true,campaignTextFlow:true,adsTopLevel:true,directAdLinks:true,adsChannelPicker:true,adChannelPickerFilter:true,strictAdChannelPicker:true,channelDisplaySanitize:true,globalAdminNameSanitize:true,rejectPersonalNameChannelTitles:true,channelTitleResolver:true,channelTitleRefreshRoute:true,channelOwnerBindRoute:true,tenantChannelBinding:true,autoTenantChannelBind:true,hybridChannelRegistry:true,getChatChannelTitles:true,connectedChannelsWithoutPosts:true,inviteLinksSupported:true,inviteInputGuard:true,adCopyLink:true,adTrackingLinks:true,trackingLinksSupported:true,clckShortLinks:true,clckShortLinksSupported:true,campaignRedirectRoute:'/r/:slug',campaignAttributionSupported:true,campaignSubscriberStats:true,channelTitleRefresh:'/debug/channel-title-refresh',channelTitleRefreshLive:'/debug/channel-title-refresh-live',channelOwnerBindLive:'/debug/channel-owner-bind-live',channelTitleResolverState,clientAccessBootstrapState,clientAccessInfo:require('./services/clientAccessService').info(),inviteInputGuardState,inviteLinkPatchState,privateWarningPatchState,adCopyLinkPatchState,adChannelPickerFilterState,strictAdChannelPickerState,postEditorTrace:postEditorTraceState,walkthroughTrace:'/debug/admin-walkthrough-trace',walkthroughTraceClear:'/debug/admin-walkthrough-trace-clear',botAuditTrace:'/debug/bot-audit-trace',botAuditTraceClear:'/debug/bot-audit-trace-clear',statsMonitoringLive:'/debug/stats-monitoring-live',statsMonitoringSelftest:'/debug/stats-monitoring-selftest',campaignLinksSelftest:'/debug/campaign-links-selftest',campaignRedirect:'/r/:slug',clckEndpoint:process.env.ADMINKIT_CLCK_ENDPOINT||'https://clck.ru/--',stickerRoutes:'stickers-live-routes-pr87.js',selftestRoutes:'comments-selftest-routes-pr88.js',browserRunner:'/debug/selftest/comments/runner',persistentStore:bootstrap.info()};}
async function start(){applyEnv();const persistentStore=await installPersistentStore();const clientAccessBootstrap=await installClientAccessRepository();const debugStoreSanitizer=installDebugStoreSanitizer();const postEditorTrace=installPostEditorTrace();const inviteInputGuard=installInviteInputGuard();const inviteLinkPatch=installInviteLinkPatch();const privateWarningPatch=installPrivateWarningPatch();const adCopyLinkPatch=installAdCopyLinkPatch();const adChannelPickerFilter=installAdChannelPickerFilter();const strictAdChannelPicker=installStrictAdChannelPicker();const channelTitleResolver=installChannelTitleResolver();const expressRoutes=installExpressRoutes();const cleanBot=installCleanBot();process.env.ADMINKIT_CLEAN_1539_EXPRESS_ROUTES_OK=expressRoutes.ok?'1':'0';process.env.ADMINKIT_CLEAN_1539_BOT_OK=cleanBot.ok?'1':'0';console.log('adminkit pr89 start',JSON.stringify({runtimeVersion:RUNTIME,persistentStore,clientAccessBootstrap,debugStoreSanitizer,postEditorTrace,inviteInputGuard,inviteLinkPatch,privateWarningPatch,adCopyLinkPatch,adChannelPickerFilter,strictAdChannelPicker,channelTitleResolver,expressRoutes,cleanBot}));return require('./index');}
if(require.main===module)start().catch((e)=>{console.error('adminkit pr89 boot failed',e&&e.stack||e);});module.exports={RUNTIME,SOURCE,BASE,applyEnv,installPersistentStore,installDebugStoreSanitizer,installPostEditorTrace,installInviteInputGuard,installInviteLinkPatch,installPrivateWarningPatch,installAdCopyLinkPatch,installAdChannelPickerFilter,installStrictAdChannelPicker,installChannelTitleResolver,installClientAccessRepository,installExpressRoutes,installCleanBot,info,start};
