'use strict';
const RUNTIME='CC7.5.38-CORE-1.53.11-ARCHIVE-KEYFLOW';
const SOURCE='adminkit-cc7-5-38-core-1-53-11-archive-keyflow';
const BASE='https://p01--amio-commnets-max--qkpwxnxqqrnw.code.run';
let persistentStoreState=null;
function applyEnv(){process.env.BUILD_VERSION=RUNTIME;process.env.RUNTIME_VERSION=RUNTIME;process.env.BUILD_SOURCE_MARKER=SOURCE;process.env.ADMINKIT_PUBLIC_BASE_URL=BASE;process.env.ADMINKIT_CLEAN_MENU_CORE='1';process.env.ADMINKIT_CLEAN_ENTRYPOINT='1.53.11';process.env.ADMINKIT_UI_TRACE='1';}
async function installPersistentStore(){const bootstrap=require('./persistent-store-bootstrap');persistentStoreState=await bootstrap.install({runtimeVersion:RUNTIME});return persistentStoreState;}
function installExpressRoutes(){const expressPath=require.resolve('express');const express=require('express');const routes=require('./v3-menu-routes-1539');if(express&&express.__adminkitClean1539Wrapped)return{ok:true,already:true,runtimeVersion:RUNTIME};function wrappedExpress(){const app=express.apply(this,arguments);routes.install(app);return app;}Object.setPrototypeOf(wrappedExpress,express);Object.assign(wrappedExpress,express);wrappedExpress.__adminkitClean1539Wrapped=true;require.cache[expressPath].exports=wrappedExpress;return{ok:true,runtimeVersion:RUNTIME,mode:'express-wrapper-1539-archive-keyflow',noModuleLoadPatch:true};}
function installCleanBot(){const botPath=require.resolve('./bot');const legacy=require('./bot');const adapter=require('./clean-bot-poll-custom-1541');const clean=adapter.createCleanBot(legacy);require.cache[botPath].exports=clean;return{ok:true,runtimeVersion:RUNTIME,mode:'bot-wrapper-1541-custom-polls',callbackTrace:true,functionalSectionsDelegateToLegacy:true,noMaxApiPatch:true};}
function info(){const bootstrap=require('./persistent-store-bootstrap');return{ok:true,runtimeVersion:RUNTIME,sourceMarker:SOURCE,canonicalPublicBaseUrl:BASE,cleanBase:true,entrypoint:'clean-entrypoint-1.53.9.js',menuCore:'v3-menu-core-1539.js',botAdapter:'clean-bot-poll-custom-1541.js',routes:'v3-menu-routes-1539.js',uiTrace:'v3-ui-trace-1539.js',archiveFlow:'archive-flow-15311.js',pollFlow:'poll-flow-15311.js',activeRuntime:'index.js',visibleMainMenuTotal:12,featurePlanTotal:17,restoredItems:['archive','tariffs'],hiddenFromMain:['navigation','landing_start','production_checklist'],debugStillVisible:true,commentsNestedItems:['photos','reactions_replies'],persistentStore:bootstrap.info(),postArchive:true,archiveKeyflow:true,customPolls:true,callbackTraceEnabled:true,noModuleLoadPatch:true,noMaxApiPatch:true,noLongEntrypointChain:true,rollback:'Set package.json start back to previous clean entrypoint/runtime'};}
async function start(){applyEnv();const persistentStore=await installPersistentStore();const expressRoutes=installExpressRoutes();const cleanBot=installCleanBot();process.env.ADMINKIT_CLEAN_1539_EXPRESS_ROUTES_OK=expressRoutes.ok?'1':'0';process.env.ADMINKIT_CLEAN_1539_BOT_OK=cleanBot.ok?'1':'0';console.log('adminkit clean 1.53.11 archive keyflow start',JSON.stringify({runtimeVersion:RUNTIME,persistentStore,expressRoutes,cleanBot}));return require('./index');}
if(require.main===module)start().catch((e)=>{console.error('adminkit archive keyflow boot failed',e&&e.stack||e);process.exit(1);});module.exports={RUNTIME,SOURCE,BASE,applyEnv,installPersistentStore,installExpressRoutes,installCleanBot,info,start};