'use strict';
const RUNTIME='CC8.2.2-ADMINKIT-COMMENTS-BROWSER-SELFTEST-PR89';
const SOURCE='adminkit-cc8-2-2-comments-browser-selftest-pr89';
const BASE='https://p01--amio-commnets-max--qkpwxnxqqrnw.code.run';
let persistentStoreState=null;
let debugStoreSanitizerState=null;
function applyEnv(){process.env.BUILD_VERSION=RUNTIME;process.env.RUNTIME_VERSION=RUNTIME;process.env.BUILD_SOURCE_MARKER=SOURCE;process.env.ADMINKIT_PUBLIC_BASE_URL=BASE;process.env.ADMINKIT_CLEAN_MENU_CORE='1';process.env.ADMINKIT_CLEAN_ENTRYPOINT='1.53.10-pr89-browser-selftest';process.env.ADMINKIT_UI_TRACE='1';if(process.env.ADMINKIT_UI_TRACE_LIMIT===undefined)process.env.ADMINKIT_UI_TRACE_LIMIT='20';if(process.env.ADMINKIT_STICKERS_ENABLED===undefined)process.env.ADMINKIT_STICKERS_ENABLED='1';if(process.env.ADMINKIT_STICKERS_PACKS===undefined)process.env.ADMINKIT_STICKERS_PACKS='adminkit_whales_v1';}
async function installPersistentStore(){const bootstrap=require('./persistent-store-bootstrap');persistentStoreState=await bootstrap.install({runtimeVersion:RUNTIME});return persistentStoreState;}
function installDebugStoreSanitizer(){const sanitizer=require('./debug-store-sanitizer-pr85');debugStoreSanitizerState=sanitizer.install();return debugStoreSanitizerState;}
function installExpressRoutes(){const expressPath=require.resolve('express');const express=require('express');const routes=require('./v3-menu-routes-1539');const performanceRoutes=require('./performance-debug-routes-pr73');const stickerRoutes=require('./stickers-live-routes-pr87');const selftestRoutes=require('./comments-selftest-routes-pr88');if(express&&express.__adminkitClean1539Wrapped)return{ok:true,already:true,runtimeVersion:RUNTIME};function wrappedExpress(){const app=express.apply(this,arguments);routes.install(app);performanceRoutes.install(app);stickerRoutes.install(app);selftestRoutes.install(app);return app;}Object.setPrototypeOf(wrappedExpress,express);Object.assign(wrappedExpress,express);wrappedExpress.__adminkitClean1539Wrapped=true;require.cache[expressPath].exports=wrappedExpress;return{ok:true,runtimeVersion:RUNTIME,mode:'express-wrapper-pr89-browser-selftest',performanceTrace:true,stickersLiveComments:true,commentsSelftest:true,commentsBrowserSelftest:true};}
function installCleanBot(){const botPath=require.resolve('./bot');const legacy=require('./bot');const adapter=require('./clean-bot-channel-fast-pr84');const clean=adapter.createCleanBot(legacy);require.cache[botPath].exports=clean;return{ok:true,runtimeVersion:RUNTIME,mode:'bot-wrapper-pr89-browser-selftest',stickersLiveComments:true,commentsSelftest:true,commentsBrowserSelftest:true};}
function info(){const bootstrap=require('./persistent-store-bootstrap');return{ok:true,runtimeVersion:RUNTIME,sourceMarker:SOURCE,entrypoint:'clean-entrypoint-1.53.10-pr89.js',stickersLiveComments:true,commentsSelftest:true,commentsBrowserSelftest:true,stickerRoutes:'stickers-live-routes-pr87.js',selftestRoutes:'comments-selftest-routes-pr88.js',browserRunner:'/debug/selftest/comments/runner',persistentStore:bootstrap.info()};}
async function start(){applyEnv();const persistentStore=await installPersistentStore();const debugStoreSanitizer=installDebugStoreSanitizer();const expressRoutes=installExpressRoutes();const cleanBot=installCleanBot();process.env.ADMINKIT_CLEAN_1539_EXPRESS_ROUTES_OK=expressRoutes.ok?'1':'0';process.env.ADMINKIT_CLEAN_1539_BOT_OK=cleanBot.ok?'1':'0';console.log('adminkit pr89 start',JSON.stringify({runtimeVersion:RUNTIME,persistentStore,debugStoreSanitizer,expressRoutes,cleanBot}));return require('./index');}
if(require.main===module)start().catch((e)=>{console.error('adminkit pr89 boot failed',e&&e.stack||e);});module.exports={RUNTIME,SOURCE,BASE,applyEnv,installPersistentStore,installDebugStoreSanitizer,installExpressRoutes,installCleanBot,info,start};
