'use strict';
const RUNTIME='CC8.2.0-ADMINKIT-STICKERS-COMMENTS-PR87';
const SOURCE='adminkit-cc8-2-0-stickers-comments-pr87';
const BASE='https://p01--amio-commnets-max--qkpwxnxqqrnw.code.run';
let persistentStoreState=null;
let debugStoreSanitizerState=null;
function applyEnv(){process.env.BUILD_VERSION=RUNTIME;process.env.RUNTIME_VERSION=RUNTIME;process.env.BUILD_SOURCE_MARKER=SOURCE;process.env.ADMINKIT_PUBLIC_BASE_URL=BASE;process.env.ADMINKIT_CLEAN_MENU_CORE='1';process.env.ADMINKIT_CLEAN_ENTRYPOINT='1.53.14-pr87-stickers';process.env.ADMINKIT_UI_TRACE='1';if(process.env.ADMINKIT_UI_TRACE_LIMIT===undefined)process.env.ADMINKIT_UI_TRACE_LIMIT='20';if(process.env.ADMINKIT_STICKERS_ENABLED===undefined)process.env.ADMINKIT_STICKERS_ENABLED='1';if(process.env.ADMINKIT_STICKERS_PACKS===undefined)process.env.ADMINKIT_STICKERS_PACKS='adminkit_whales_v1';}
async function installPersistentStore(){const bootstrap=require('./persistent-store-bootstrap');persistentStoreState=await bootstrap.install({runtimeVersion:RUNTIME});return persistentStoreState;}
function installDebugStoreSanitizer(){const sanitizer=require('./debug-store-sanitizer-pr85');debugStoreSanitizerState=sanitizer.install();return debugStoreSanitizerState;}
function installExpressRoutes(){const expressPath=require.resolve('express');const express=require('express');const routes=require('./v3-menu-routes-1539');const performanceRoutes=require('./performance-debug-routes-pr73');const stickerRoutes=require('./stickers-live-routes-pr87');if(express&&express.__adminkitClean1539Wrapped)return{ok:true,already:true,runtimeVersion:RUNTIME};function wrappedExpress(){const app=express.apply(this,arguments);routes.install(app);performanceRoutes.install(app);stickerRoutes.install(app);return app;}Object.setPrototypeOf(wrappedExpress,express);Object.assign(wrappedExpress,express);wrappedExpress.__adminkitClean1539Wrapped=true;require.cache[expressPath].exports=wrappedExpress;return{ok:true,runtimeVersion:RUNTIME,mode:'express-wrapper-1539-ui20-channel-safe-pr73-performance-trace-pr84-pr85-pr87-stickers',performanceTrace:true,noModuleLoadPatch:true,patchTimingClear:true,stickersLiveComments:true,stickersNativeMaxProbe:false};}
function installCleanBot(){const botPath=require.resolve('./bot');const legacy=require('./bot');const adapter=require('./clean-bot-channel-fast-pr84');const clean=adapter.createCleanBot(legacy);require.cache[botPath].exports=clean;return{ok:true,runtimeVersion:RUNTIME,mode:'bot-wrapper-pr84-fast-channel-patch-posts-open-async-delivery-pr85-debug-sanitized-pr87-stickers',functionalSectionsDelegateToLegacy:true,oneActiveInputFlow:true,channelAdminCallbackGuard:true,accountCabinet:true,postsTextFlowHotfix:true,postsStagedSave:true,postsAsyncPatch:true,postsFastOpen:true,postsOpenAsyncDelivery:true,uiTraceAlwaysOn:true,noMaxApiPatch:true,directChannelFastPatchPr84:true,fastPatchNoBootstrapDb:true,botAdapter:'clean-bot-channel-fast-pr84.js',debugStoreSanitized:true,moderationLogsBase64Stripped:true,stickersLiveComments:true};}
function info(){const bootstrap=require('./persistent-store-bootstrap');return{ok:true,runtimeVersion:RUNTIME,sourceMarker:SOURCE,canonicalPublicBaseUrl:BASE,cleanBase:true,entrypoint:'clean-entrypoint-1.53.9.js',menuCore:'v3-menu-core-1539.js',postsTextFlow:'posts-flow-cc8-text-flow.js',postEditorFastText:'services/postEditorFastTextService.js',botAdapter:'clean-bot-channel-fast-pr84.js',fastPatchRuntime:'CC8.1.19-DIRECT-CHANNEL-FAST-PATCH-NO-BOOTSTRAP-DB-PR84',debugStoreSanitizer:'debug-store-sanitizer-pr85.js',debugStoreSanitized:true,moderationLogsBase64Stripped:true,moderationLogLimit:50,patchTimingClear:true,stickersFoundation:true,stickersLiveComments:true,stickersNativeMaxProbe:false,stickersPack:'adminkit_whales_v1',accountRuntime:'src/core/accountRuntime.js',accountCabinet:'src/core/accountCabinet.js',routes:'v3-menu-routes-1539.js',archiveFlow:'archive-flow-15311.js',pollFlow:'poll-flow-15313.js',highlightFlow:'highlight-flow-15311.js',highlightTrace:'highlight-debug-trace.js',uiTrace:'v3-ui-trace-1539.js',postPatcher:'services/postPatcherFastPr84.js',performanceTrace:'performance-debug-routes-pr73.js',stickerRoutes:'stickers-live-routes-pr87.js',persistentStore:bootstrap.info(),postArchive:true,archiveKeyflow:true,customPolls:true,steppedPollWizard:true,highlightsTrace:true,flowGuard:true,oneActiveInputFlow:true,channelAdminCallbackGuard:true,accountCabinet:true,postsTextFlowHotfix:true,postsStagedSave:true,postsAsyncPatch:true,postsFastOpen:true,postsOpenAsyncDelivery:true,uiTraceAlwaysOn:true,uiTraceLimit:20,safeKeyboardCompose:true,preservesPollsWhenAddingButtons:true,performanceTraceEnabled:true,noModuleLoadPatch:true,noMaxApiPatch:true,directChannelFastPatchPr84:true,fastPatchNoBootstrapDb:true};}
async function start(){applyEnv();const persistentStore=await installPersistentStore();const debugStoreSanitizer=installDebugStoreSanitizer();const expressRoutes=installExpressRoutes();const cleanBot=installCleanBot();process.env.ADMINKIT_CLEAN_1539_EXPRESS_ROUTES_OK=expressRoutes.ok?'1':'0';process.env.ADMINKIT_CLEAN_1539_BOT_OK=cleanBot.ok?'1':'0';console.log('adminkit account cabinet start',JSON.stringify({runtimeVersion:RUNTIME,persistentStore,debugStoreSanitizer,expressRoutes,cleanBot}));return require('./index');}
if(require.main===module)start().catch((e)=>{console.error('adminkit account cabinet boot failed',e&&e.stack||e);});module.exports={RUNTIME,SOURCE,BASE,applyEnv,installPersistentStore,installDebugStoreSanitizer,installExpressRoutes,installCleanBot,info,start};
