'use strict';

require('./v3-silent-menu-callbacks').install();
require('./v3-comments-launch-fix').install();
require('./v3-repatch-comments-links').install();
require('./v3-register-post-debug').install();
require('./clean-v3-main-route-guard').install();
require('./clean-v3-menu-normalizer').install();
require('./clean-v3-comments-banner-action').install();
require('./clean-v3-comments-banner-router-fix').install();
require('./clean-v3-comments-function-points-v2').install();
require('./clean-v3-menu-debug').install();
require('./clean-v3-menu-ok').install();
require('./production-menu-v3-renderer-v2').install();
require('./production-menu-map-v3-fixed-debug').install();
require('./cc6542-hotfix-router').install();
require('./v3-native-hints-cleanup').install();
require('./v3-openapp-payload-bridge').install();
require('./cc5-bootstrap-lite');
require('./v3-disable-growth-cta').install();
