'use strict';

const RUNTIME = 'SP40.5.8-clear-core';
const SOURCE = 'adminkit-SP40.5.8-safe-comments-moderation-buttons';
console.log(`[${RUNTIME}] safe wrapper: comments UI + moderation callbacks`);
process.env.BUILD_VERSION = RUNTIME;
process.env.RUNTIME_VERSION = RUNTIME;
process.env.BUILD_SOURCE_MARKER = SOURCE;

const fs = require('fs');
const path = require('path');
const Module = require('module');

function norm(v){return String(v||'').replace(/^post:/i,'').replace(/^:+/,'').replace(/^['\"]+|['\"]+$/g,'').trim();}
function cut(v,n=70){const s=String(v||'').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n-1)+'…':s;}
function btn(text,action,extra={}){return{type:'callback',text,payload:JSON.stringify({action,...extra})};}
function kb(rows){return[{type:'inline_keyboard',payload:{buttons:rows}}];}
function parsePayload(v){if(v&&typeof v==='object')return v;const s=String(v||'').trim();if(!s)return{};try{const p=JSON.parse(s);return p&&typeof p==='object'?p:{action:s};}catch{return{action:s};}}
function deep(obj,keys,seen=new Set()){if(!obj||typeof obj!=='object'||seen.has(obj))return'';seen.add(obj);const set=new Set(keys.map(k=>String(k).toLowerCase()));for(const[k,v]of Object.entries(obj)){if(set.has(String(k).toLowerCase())){const s=String(v||'').trim();if(s&&s!=='[object Object]')return s;}}for(const v of Object.values(obj)){const f=deep(v,keys,seen);if(f)return f;}return'';}
function cb(u={}){return u.callback||u.data?.callback||u.message?.callback||u.update?.callback||null;}
function msg(u={}){return u.message||u.data?.message||u.callback?.message||u.data?.callback?.message||null;}
function payload(u={}){const c=cb(u)||{};return parsePayload(c.payload||c.data||c.callback_data||c.value||deep(c,['payload','data','callback_data']));}
function callbackId(u={}){const c=cb(u)||{};return String(c.callback_id||c.callbackId||c.id||deep(c,['callback_id','callbackId'])||'').trim();}
function userId(u={}){return String(deep(u,['user_id','userId','sender_id','from_id','id'])||'').trim();}
function chatId(u={}){const m=msg(u)||{};return String(m.recipient?.chat_id||m.recipient?.id||m.chat_id||m.chat?.id||deep(m,['chat_id'])||'').trim();}
function textOf(u={}){const m=msg(u)||{};return String(m.body?.text||m.text||m.message?.text||'').trim();}
function has(a,parts){const s=String(a||'').toLowerCase();return parts.every(p=>s.includes(String(p).toLowerCase()));}
function noCache(res){res.set({'Cache-Control':'no-store, no-cache, must-revalidate, max-age=0',Pragma:'no-cache',Expires:'0'});}
function adminOk(req,res){const exp=String(process.env.MODERATION_ADMIN_TOKEN||process.env.GIFT_ADMIN_TOKEN||process.env.ADMIN_TOKEN||'').trim();const got=String(req.query?.token||req.query?.adminToken||req.get?.('x-admin-token')||'').trim();if(!exp||got===exp)return true;noCache(res);res.status(403).json({ok:false,error:'admin_forbidden',runtimeVersion:RUNTIME});return false;}
function st(){return require('./store');}
function channels(){try{return require('./services/channelService').listChannels?.()||[];}catch{return[];}}
function firstChannel(id=''){const w=String(id||'').trim();const list=channels();return list.find(c=>String(c.channelId||'')===w)||list.find(c=>String(c.channelId||'').trim())||null;}
function channelTitle(id=''){const c=firstChannel(id)||{};return String(c.title||c.channelTitle||c.name||c.chatTitle||c.channelName||id||'Канал').trim();}
function postChannel(commentKey=''){const key=norm(commentKey);try{const p=st().getPost?.(key);if(p?.channelId)return String(p.channelId).trim();}catch{}return key.includes(':')?key.split(':')[0]:'';}
function scopeFrom(p={}){const raw=String(p.scope||p.scopeKey||'').trim();const commentKey=norm(p.commentKey||p.key||(/^post:/i.test(raw)?raw:''));let channelId=String(p.channelId||p.channel||'').trim();if(!channelId&&commentKey)channelId=postChannel(commentKey);if(!channelId)channelId=String(firstChannel()?.channelId||'').trim();return{scope:commentKey?'post':'channel',commentKey,channelId};}
function getSettings(scope){const s=st();if(scope.scope==='post'&&scope.commentKey&&typeof s.getPostModerationSettings==='function'){return s.getPostModerationSettings(scope.commentKey)||{...(s.getModerationSettings?.(scope.channelId)||{}),scope:'post',commentKey:scope.commentKey,channelId:scope.channelId};}return s.getModerationSettings?.(scope.channelId)||{};}
function saveSettings(scope,next){const s=st();if(scope.scope==='post'&&scope.commentKey&&typeof s.savePostModerationSettings==='function')return s.savePostModerationSettings(scope.commentKey,{...next,channelId:scope.channelId});return s.saveModerationSettings?.(scope.channelId,next);}
function listPosts(channelId=''){const s=st();if(typeof s.listModerationScopeOptions==='function')return s.listModerationScopeOptions(channelId,20).posts||[];return(s.listPostsByChannel?.(channelId,20)||[]).map(p=>({commentKey:p.commentKey,channelId:p.channelId,title:cut(p.originalText||p.text||'Пост без текста')}));}
function moderationMenu(scope){const set=getSettings(scope);const enabled=set.enabled!==false;const preset=set.applyPresetCommon!==false;const links=Boolean(set.blockLinks);const invites=set.blockInvites!==false;const custom=Array.isArray(set.customBlocklist)?set.customBlocklist:[];const post=scope.scope==='post'&&scope.commentKey?st().getPost?.(scope.commentKey):null;const area=scope.scope==='post'?'правила только этого поста':'правила всего канала';const ctx={scope:scope.scope,channelId:scope.channelId,commentKey:scope.commentKey};return{text:['Модерация комментариев','',`Канал: ${channelTitle(scope.channelId)}`,`Область: ${area}`,post?.originalText?`Пост: ${cut(post.originalText,92)}`:'',`Фильтр: ${enabled?'включён':'выключен'}`,`Стоп-слова: ${preset?'базовый список включён':'базовый список выключен'}`,`Ручной список: ${custom.length?custom.join(', '):'пока пусто'}`,`Ссылки: ${links?'блокируются':'разрешены'}`,`Приглашения: ${invites?'блокируются':'разрешены'}`,`AI-модерация: ${set.aiEnabled?'включена':'выключена / PRO'}`,'','Выберите правило кнопками ниже.'].filter(Boolean).join('\n'),attachments:kb([[btn('📺 Выбрать другой канал/пост','ak_mod_choose_scope',{channelId:scope.channelId})],[btn(scope.scope==='post'?'🛡 Правила этого поста':'🛡 Правила всего канала','ak_mod_noop',ctx)],[btn(enabled?'⏸ Выключить фильтр':'▶️ Включить фильтр','ak_mod_toggle_enabled',ctx)],[btn(preset?'🧱 Стоп-слова: вкл.':'🧱 Стоп-слова: выкл.','ak_mod_toggle_preset',ctx)],[btn('➕ Стоп-слово','ak_mod_add_stopword',ctx),btn('🧹 Очистить ручные','ak_mod_clear_stopwords',ctx)],[btn(links?'🔗 Ссылки: блок.':'🔗 Ссылки: разреш.','ak_mod_toggle_links',ctx),btn(invites?'✉️ Инвайты: блок.':'✉️ Инвайты: разреш.','ak_mod_toggle_invites',ctx)],[btn('🤖 AI: PRO','ak_mod_ai_pro',ctx)],[btn('🏠 Главное меню','ak_main_menu',{})]])};}
function chooseScopeMenu(channelId=''){const ch=firstChannel(channelId);const resolved=String(channelId||ch?.channelId||'').trim();const posts=listPosts(resolved);const rows=[];if(resolved)rows.push([btn('🛡 Весь канал','ak_mod_scope_channel',{channelId:resolved})]);posts.slice(0,12).forEach((p,i)=>rows.push([btn(`Пост ${i+1}: ${cut(p.title,44)}`,'ak_mod_pick_post',{channelId:p.channelId,commentKey:p.commentKey})]));rows.push([btn('↩️ В начало модерации','ak_mod_start',{channelId:resolved})]);return{text:['Выберите область модерации','',resolved?`Канал: ${channelTitle(resolved)}`:'Канал пока не выбран.','',posts.length?'Можно настроить правила для всего канала или отдельно для конкретного поста.':'Посты пока не найдены. Перешлите нужный пост боту, затем вернитесь в модерацию.'].join('\n'),attachments:kb(rows)};}
async function send(u,p){const api=require('./services/maxApi');const cfg=require('./config');const uid=userId(u);const cid=chatId(u);return api.sendMessage({botToken:cfg.botToken,userId:uid||undefined,chatId:uid?undefined:cid||undefined,text:p.text,attachments:p.attachments});}
async function answer(u,n){const id=callbackId(u);if(!id)return null;try{return await require('./services/maxApi').answerCallback({botToken:require('./config').botToken,callbackId:id,notification:n});}catch{return null;}}
function setFlow(uid,flow){if(!uid)return;const s=st();const cur=s.getSetupState?.(uid)||{};s.setSetupState?.(uid,{...cur,akModFlow:flow,updatedAt:Date.now()});}
function getFlow(uid){return uid?st().getSetupState?.(uid)?.akModFlow||null:null;}
function clearFlow(uid){if(!uid)return;const s=st();const cur=s.getSetupState?.(uid)||{};if(!cur.akModFlow)return;delete cur.akModFlow;s.setSetupState?.(uid,cur);}
async function handleModeration(u={}){const uid=userId(u);const txt=textOf(u);const flow=getFlow(uid);if(flow?.type==='add_stopword'&&txt){const scope=scopeFrom(flow);const cur=getSettings(scope);const words=[...new Set(txt.split(/[\n,;]+/g).map(w=>w.trim().toLowerCase()).filter(Boolean))];const customBlocklist=[...new Set([...(Array.isArray(cur.customBlocklist)?cur.customBlocklist:[]),...words])];saveSettings(scope,{...cur,customBlocklist});clearFlow(uid);await send(u,{text:`Добавлено: ${words.join(', ')||'ничего'}`,attachments:[]});await send(u,moderationMenu(scope));return true;}const p=payload(u);const action=String(p.action||p.type||'').trim();if(!action)return false;const known=action.startsWith('ak_mod_')||has(action,['stop','word'])||has(action,['moderation']);if(!known)return false;const scope=scopeFrom(p);if(action==='ak_mod_choose_scope'||has(action,['choose','scope'])||has(action,['select','post'])){await answer(u,'Выберите область');await send(u,chooseScopeMenu(scope.channelId));return true;}if(action==='ak_mod_start'||action==='ak_mod_scope_channel'){await answer(u,'Правила канала');await send(u,moderationMenu({scope:'channel',channelId:scope.channelId,commentKey:''}));return true;}if(action==='ak_mod_pick_post'){await answer(u,'Правила поста');await send(u,moderationMenu(scope));return true;}if(action==='ak_mod_add_stopword'||has(action,['stop','word','add'])){setFlow(uid,{type:'add_stopword',...scope});await answer(u,'Пришлите стоп-слово');await send(u,{text:'Пришлите стоп-слово или несколько слов через запятую. Они будут добавлены именно в текущую область модерации.',attachments:kb([[btn('↩️ Отмена','ak_mod_cancel',scope)]])});return true;}if(action==='ak_mod_cancel'){clearFlow(uid);await answer(u,'Отменено');await send(u,moderationMenu(scope));return true;}if(action==='ak_mod_clear_stopwords'){const cur=getSettings(scope);saveSettings(scope,{...cur,customBlocklist:[]});await answer(u,'Очищено');await send(u,moderationMenu(scope));return true;}const cur=getSettings(scope);const next={...cur};if(action==='ak_mod_toggle_enabled')next.enabled=cur.enabled===false;else if(action==='ak_mod_toggle_preset')next.applyPresetCommon=cur.applyPresetCommon===false;else if(action==='ak_mod_toggle_links')next.blockLinks=!cur.blockLinks;else if(action==='ak_mod_toggle_invites')next.blockInvites=cur.blockInvites===false;else if(action==='ak_mod_ai_pro'){await answer(u,'AI — PRO');await send(u,{text:'AI-модерация будет отдельной PRO-функцией. Сейчас стабилизируем базовую модерацию.',attachments:kb([[btn('↩️ Назад','ak_mod_start',scope)]])});return true;}else if(action==='ak_mod_noop'){await answer(u,'Текущая область уже выбрана');return true;}else return false;saveSettings(scope,next);await answer(u,'Сохранено');await send(u,moderationMenu(scope));return true;}
function patchBot(bot){if(!bot||bot.__ak58Bot)return bot;bot.__ak58Bot=true;for(const k of Object.keys(bot)){if(typeof bot[k]!=='function')continue;const old=bot[k];bot[k]=async function(...args){const u=args.find(a=>a&&typeof a==='object'&&(a.message||a.callback||a.data||a.update))||args[0];try{if(await handleModeration(u||{}))return{ok:true,handledBy:RUNTIME};}catch(e){console.error(`[${RUNTIME}] moderation wrapper failed`,e?.message||e);}return old.apply(this,args);};}return bot;}
function rewriteButton(b={}){if(!b||typeof b!=='object')return b;const t=String(b.text||'').trim();if(/выбрать.*канал.*пост/i.test(t))return btn(t,'ak_mod_choose_scope',{});if(/стоп-слово/i.test(t)&&/\+|➕|добав/i.test(t))return btn(t,'ak_mod_add_stopword',{});if(/очистить.*руч/i.test(t))return btn(t,'ak_mod_clear_stopwords',{});if(/правила всего канала/i.test(t))return btn(t,'ak_mod_scope_channel',{});return b;}
function rewriteAttachments(a){if(!Array.isArray(a))return a;return a.map(x=>x?.type==='inline_keyboard'&&Array.isArray(x.payload?.buttons)?{...x,payload:{...x.payload,buttons:x.payload.buttons.map(r=>Array.isArray(r)?r.map(rewriteButton):r)}}:x);}
function patchMaxApi(api){if(!api||api.__ak58Max)return api;api.__ak58Max=true;for(const name of['sendMessage','editMessage']){if(typeof api[name]!=='function')continue;const old=api[name].bind(api);api[name]=(args={})=>/Модерация комментариев|Стоп-слова|AI-модерация|Область: правила/i.test(String(args.text||''))?old({...args,attachments:rewriteAttachments(args.attachments)}):old(args);}return api;}
function patchAppJsText(t){let out=String(t||'');out=out.replace(/\n;\(\(\) => \{\n  if \(window\.__ADMINKIT_SP4057_CLEAR_CORE__\)[\s\S]*?\n\}\)\(\);\n?/,'\n');out=out.replace(/function renderLeadMagnet\(growth\) \{[\s\S]*?\n\}\n\nfunction renderTrackedButtons/,['function renderLeadMagnet(growth) {','  if (!growthLeadCard) return;','  const lead = growth && growth.leadMagnet ? growth.leadMagnet : null;',"  const leadUrl = String((lead && (lead.trackedUrl || lead.targetUrl)) || '').trim();","  if (!lead || lead.enabled === false || !leadUrl) { growthLeadCard.innerHTML = ''; growthLeadCard.classList.add('hidden'); return; }","  growthLeadCard.innerHTML = '<div class=\"growth-section-head\"><strong>Полезная ссылка</strong><span>CTA для этого обсуждения</span></div><a class=\"growth-button growth-button-secondary\" href=\"' + escapeHtml(leadUrl) + '\">' + escapeHtml(lead.text || 'Перейти') + '</a>';","  growthLeadCard.classList.remove('hidden');",'}','','function renderTrackedButtons'].join('\n'));return out;}
function installFinalAppPatch(){if(fs.__ak58FinalReadPatch)return;fs.__ak58FinalReadPatch=true;const read=fs.readFileSync.bind(fs);const appPath=path.resolve(path.join(__dirname,'public','app.js'));fs.readFileSync=function(filePath,options){const c=read(filePath,options);try{const textMode=options==='utf8'||options==='utf-8'||(options&&typeof options==='object'&&/utf-?8/i.test(String(options.encoding||'')));if(path.resolve(String(filePath||''))===appPath&&textMode)return patchAppJsText(String(c||''));}catch{}return c;};}
function installRoutes(app){if(!app||app.__ak58Routes)return app;app.__ak58Routes=true;app.get('/debug/clear-core',(req,res)=>{if(!adminOk(req,res))return;noCache(res);let scopeCounts={postScopes:0,channels:0};try{const root=st().store||{};scopeCounts={postScopes:Object.keys(root.moderation?.byPost||{}).length,channels:Object.keys(root.moderation?.byChannel||{}).length};}catch{}res.json({ok:true,runtimeVersion:RUNTIME,sourceMarker:SOURCE,generatedAt:Date.now(),fixes:['restore_comments_screen','post_moderation_callbacks','post_moderation_scope','comments_cta_safe'],scopeCounts});});return app;}
const oldLoad=Module._load;
Module._load=function(request,parent,isMain){const loaded=oldLoad.apply(this,arguments);const r=String(request||'');try{if(r.includes('services/maxApi')&&loaded)return patchMaxApi(loaded);if((r==='./bot'||r.endsWith('/bot')||r.endsWith('bot.js'))&&loaded)return patchBot(loaded);if(r==='express'&&loaded&&!loaded.__ak58Wrapped){function wrapped(...args){return installRoutes(loaded(...args));}Object.setPrototypeOf(wrapped,loaded);Object.assign(wrapped,loaded);wrapped.__ak58Wrapped=true;return wrapped;}}catch(e){console.warn(`[${RUNTIME}] patch skipped for ${r}:`,e?.message||e);}return loaded;};
require('./server-sp4057.js');
installFinalAppPatch();
process.env.BUILD_VERSION=RUNTIME;
process.env.RUNTIME_VERSION=RUNTIME;
process.env.BUILD_SOURCE_MARKER=SOURCE;
