require('./v3live').install()
require('./production-menu-v3-renderer-v2').install()
require('./production-menu-map-v3-fixed-debug').install()
require('./cc6542-hotfix-router').install()
require('./cc5-bootstrap-lite')
