'use strict';
const {getGiftClaim,getComments,getReactionsMap,listGrowthPollVotes,normalizeKey}=require('../store');
const {getChatMembers}=require('./maxApi');
const s=(v)=>String(v||'').trim();
const a=(v)=>Array.isArray(v)?v:[];
const low=(v)=>s(v).toLowerCase();
const norm=(v)=>s(v).replace(/\s+/g,' ').toLowerCase();
function channelFromCommentKey(key=''){const k=normalizeKey(key||'');return k&&k.includes(':')?s(k.split(':')[0]):'';}
function active(c={}){const explicit=c.conditionsConfig&&typeof c.conditionsConfig==='object'&&Array.isArray(c.conditionsConfig.items);if(explicit)return{explicit:true,logic:s(c.conditionsConfig.logic).toUpperCase()==='OR'?'OR':'AND',items:c.conditionsConfig.items.filter(x=>x&&x.enabled!==false)};const items=[];const chat=s(c.requiredChatId||c.channelId||channelFromCommentKey(c.commentKey));if(chat||c.subscribeUrl||c.notSubscribedNotification)items.push({type:'subscription',mode:'all',channels:chat?[{channelId:chat}]:[]});if(c.onlyOnce!==false)items.push({type:'firstTimeOnly'});return{explicit:false,logic:'AND',items};}
function channels(item={},c={}){const xs=a(item.channels).map(x=>s(x.channelId||x.chatId||x.id||x.value)).filter(Boolean);const fb=s(c.requiredChatId||c.channelId||channelFromCommentKey(c.commentKey));return[...new Set((xs.length?xs:[fb]).filter(Boolean))];}
async function sub({botToken,campaign,item,userId}){const ch=channels(item,campaign);if(!ch.length)return{type:'subscription',ok:false,reason:'channels_missing'};const mode=low(item.mode)==='any'?'any':'all';const results=[];for(const chatId of ch){try{const r=await getChatMembers({botToken,chatId,userIds:[userId]});const ok=a(r&&r.members).length>0;results.push({chatId,ok});}catch(e){results.push({chatId,ok:false,reason:'api_error',status:e&&e.status||0,message:e&&e.message||'subscription_check_failed'});}}return{type:'subscription',ok:mode==='any'?results.some(x=>x.ok):results.every(x=>x.ok),mode,results};}
function once({campaign,userId}){const ex=getGiftClaim(campaign.id,userId);return{type:'firstTimeOnly',ok:!ex||!ex.deliveredAt,reason:ex&&ex.deliveredAt?'already_claimed':''};}
function promo({item,providedCode}){const codes=a(item.codes).map(s).filter(Boolean);if(!codes.length)return{type:'promoCode',ok:false,reason:'codes_missing'};if(!s(providedCode))return{type:'promoCode',ok:false,needsInput:true,reason:'code_required'};const ok=codes.some(c=>item.caseSensitive?s(c)===s(providedCode):norm(c)===norm(providedCode));return{type:'promoCode',ok,reason:ok?'':'wrong_code'};}
function commentUid(c={}){return s(c.userId||c.user_id||c.senderId||c.sender_id||c.authorId||c.author_id||c.user&&c.user.id||c.sender&&c.sender.id);}
function commentText(c={}){return s(c.text||c.message||c.body&&c.body.text||c.body||c.value||c.content);}
function keyword({campaign,item,userId}){const words=a(item.keywords).map(s).filter(Boolean);if(!words.length)return{type:'keyword',ok:false,reason:'keywords_missing'};const key=normalizeKey(campaign.commentKey||'');if(!key)return{type:'keyword',ok:false,reason:'comment_key_missing'};const mine=a(getComments(key)).filter(c=>commentUid(c)===s(userId));const exact=low(item.matchMode)==='exact';const cs=!!item.caseSensitive;const ok=mine.some(c=>{const t=commentText(c);return words.some(w=>cs?(exact?t===w:t.includes(w)):(exact?low(t)===low(w):low(t).includes(low(w))));});return{type:'keyword',ok,reason:ok?'':'keyword_comment_missing',commentsChecked:mine.length};}
function reaction({campaign,userId}){const key=normalizeKey(campaign.commentKey||'');if(!key)return{type:'reaction',ok:false,reason:'comment_key_missing'};const map=getReactionsMap(key);let ok=false;Object.values(map||{}).forEach(byEmoji=>Object.values(byEmoji||{}).forEach(byUser=>{if(byUser&&byUser[s(userId)]===true)ok=true;}));return{type:'reaction',ok,reason:ok?'':'reaction_not_found'};}
function poll({campaign,item,userId}){const pollId=s(item.pollId||item.id||item.value);if(!pollId)return{type:'pollVote',ok:false,reason:'poll_id_missing'};const channelId=campaign.channelId||campaign.requiredChatId||channelFromCommentKey(campaign.commentKey)||'';const votes=listGrowthPollVotes({channelId,pollId});const post=s((campaign.postIds||[])[0]||campaign.postId||'');const key=normalizeKey(campaign.commentKey||'');const ok=a(votes).some(v=>s(v.userId)===s(userId)&&(!post||s(v.postId)===post)&&(!key||normalizeKey(v.commentKey||'')===key));return{type:'pollVote',ok,reason:ok?'':'poll_vote_not_found'};}
function ts(v){if(v===undefined||v===null||v==='')return 0;if(Number.isFinite(Number(v)))return Number(v);const p=Date.parse(String(v));return Number.isFinite(p)?p:0;}
function validTz(tz=''){if(!s(tz))return true;try{new Intl.DateTimeFormat('en-US',{timeZone:tz}).format(new Date());return true;}catch{return false;}}
function validDateParts(y,mo,d,h=0,mi=0){if(!Number.isInteger(y)||!Number.isInteger(mo)||!Number.isInteger(d)||!Number.isInteger(h)||!Number.isInteger(mi))return false;if(y<1970||mo<0||mo>11||d<1||h<0||h>23||mi<0||mi>59)return false;const max=new Date(Date.UTC(y,mo+1,0)).getUTCDate();return d<=max;}
function tzOffset(utcMs,tz){if(!tz)return 0;if(!validTz(tz))return null;const parts=new Intl.DateTimeFormat('en-US',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(new Date(utcMs)).reduce((m,p)=>{m[p.type]=p.value;return m;},{});const asUtc=Date.UTC(Number(parts.year),Number(parts.month)-1,Number(parts.day),Number(parts.hour),Number(parts.minute),Number(parts.second));return asUtc-utcMs;}
function zoneTs(y,mo,d,h,mi,tz){if(!validDateParts(y,mo,d,h,mi))return NaN;const utc=Date.UTC(y,mo,d,h,mi,0,0);if(!tz)return new Date(y,mo,d,h,mi,0,0).getTime();const off=tzOffset(utc,tz);if(off===null)return NaN;let out=utc-off;const off2=tzOffset(out,tz);if(off2===null)return NaN;out=utc-off2;return out;}
function parseRawDates(text='',tz=''){const out=[];const iso=/(\d{4})-(\d{1,2})-(\d{1,2})(?:[T\s]+(\d{1,2}):?(\d{2})?)?/g;let m;while((m=iso.exec(text))){const d=zoneTs(Number(m[1]),Number(m[2])-1,Number(m[3]),Number(m[4]||0),Number(m[5]||0),tz);if(Number.isFinite(d))out.push(d);else return [];}if(out.length)return out;const dm=/(\d{1,2})[.\/](\d{1,2})(?:[.\/](\d{2,4}))?\s*(\d{1,2})?:?(\d{2})?/g;while((m=dm.exec(text))){const year=Number(m[3]?(m[3].length===2?'20'+m[3]:m[3]):new Date().getFullYear());const d=zoneTs(year,Number(m[2])-1,Number(m[1]),Number(m[4]||0),Number(m[5]||0),tz);if(Number.isFinite(d))out.push(d);else return [];}return out;}
function rawTs(raw='',tz=''){const text=s(raw);if(!text)return{};if(tz&&!validTz(tz))return{invalidTimezone:true};const dates=parseRawDates(text,tz);return{start:dates[0]||0,end:dates[1]||0};}
function time({item,now=Date.now()}){const tz=s(item.timezone||item.tz||item.timeZone);const raw=rawTs(item.raw||item.value||item.text,tz);if(raw.invalidTimezone)return{type:'timeWindow',ok:false,reason:'time_window_invalid_timezone'};const start=ts(item.startAt||item.from||item.start||item.startTime)||raw.start;const end=ts(item.endAt||item.to||item.end||item.endTime)||raw.end;if(!start&&!end)return{type:'timeWindow',ok:false,reason:'time_window_unparsed'};if(start&&now<start)return{type:'timeWindow',ok:false,reason:'too_early'};if(end&&now>end)return{type:'timeWindow',ok:false,reason:'too_late'};return{type:'timeWindow',ok:true};}
function prompt(){return['🔑 Для получения подарка введите кодовое слово или промокод.','','Отправьте код одним сообщением.'].join('\n');}
function failText(checks=[]){const names={subscription:'подписка',promoCode:'промокод',keyword:'ключевое слово',reaction:'реакция',pollVote:'голос в опросе',firstTimeOnly:'первое получение',timeWindow:'окно по времени'};const bad=a(checks).filter(x=>!x.ok&&!x.needsInput).slice(0,3).map(x=>names[x.type]||x.type);return bad.length?`Сначала выполните условие: ${bad.join(', ')}`:'Сначала выполните условия получения подарка';}
async function evaluateGiftConditions({botToken,campaign,userId,providedCode='',now=Date.now()}={}){const cfg=active(campaign||{});const checks=[];if(!cfg.items.length)return{ok:true,status:'no_conditions',logic:cfg.logic,checks};for(const item of cfg.items){const t=s(item.type);if(t==='subscription')checks.push(await sub({botToken,campaign,item,userId}));else if(t==='firstTimeOnly')checks.push(once({campaign,userId}));else if(t==='promoCode')checks.push(promo({item,providedCode}));else if(t==='keyword')checks.push(keyword({campaign,item,userId}));else if(t==='reaction')checks.push(reaction({campaign,userId}));else if(t==='pollVote')checks.push(poll({campaign,item,userId}));else if(t==='timeWindow')checks.push(time({item,now}));else checks.push({type:t,ok:false,reason:'unknown_condition'});}const ok=cfg.logic==='OR'?checks.some(x=>x.ok):checks.every(x=>x.ok);if(ok)return{ok:true,status:checks.length?'conditions_met':'no_conditions',logic:cfg.logic,checks};const need=checks.find(x=>x.needsInput);if(need)return{ok:false,status:'condition_input_required',inputType:need.type,promptText:prompt(),notification:'Введите кодовое слово в личных сообщениях боту',logic:cfg.logic,checks};return{ok:false,status:'conditions_not_met',notification:failText(checks),logic:cfg.logic,checks};}
module.exports={active,evaluateGiftConditions,prompt,failText,rawTs,tzOffset,zoneTs,validTz,parseRawDates,validDateParts};