'use strict';

const menuCore=require('../v3-menu-core-1539');
const trace=require('../admin-walkthrough-trace');
const access=require('./clientAccessService');
const gate=require('./accessGateService');
const account=require('../features/account-screens-pr106');
const registry=require('./maxCommandRegistryService');
const PUBLIC_GROUP_COMMANDS=registry.GLOBAL_COMMAND_NAMES;
const ADMIN_PRIVATE_COMMANDS=Object.freeze(['/start','/menu','/channels','/comments','/gifts','/buttons','/highlight','/polls','/posts','/archive','/moderation','/stats','/account','/debug','/help','/terms','/privacy','/clear']);
const COMMANDS=new Set([...PUBLIC_GROUP_COMMANDS,...ADMIN_PRIVATE_COMMANDS]);
const ROUTES={'/start':'main:home','/menu':'main:home','/channels':'channels:home','/comments':'comments:home','/gifts':'gifts:home','/buttons':'buttons:home','/highlight':'highlight:home','/polls':'polls:home','/posts':'editor:home','/archive':'archive:home','/moderation':'moderation:home','/stats':'stats:home','/account':'account:home','/debug':'debug:home','/help':'help:home','/terms':'terms:home','/privacy':'privacy:home'};
const CONTRACT=Object.freeze({slashSingleActiveMenuContractOk:true,slashPrivateCommandsUseSingleActiveMenu:true,slashPrivateSlashSkipsPreCleanup:true,slashPrivateUpsertTargetsLatestBotMenu:true,slashClearKeepsExplicitCleanup:true,slashGroupDeniedUsesGroupHelp:true,slashGroupPushDoesNotRenderPrivateAdminScreen:true,slashSingleActiveOnlyPrivateAdminCommands:true,slashPreviewCatalogExternal:true,slashDesiredGlobalCommandsOnlyPushHelp:true});
function clean(v){return String(v||'').trim();}
function first(...xs){for(const x of xs){const t=clean(x);if(t)return t;}return '';}
function getNativeSlashCommand(text=''){const raw=clean(text);if(!raw.startsWith('/'))return'';const command=(raw.split(/\s+/)[0]||'').replace(/@[\w.:-]+$/i,'').trim().toLowerCase();return COMMANDS.has(command)?command:'';}
function pos(v){if(v===undefined||v===null||v==='')return false;const n=Number(v);return Number.isFinite(n)?n>0:Boolean(v);}
function hints(s={}){return Boolean(s.is_group||s.isGroup||s.is_public||s.isPublic||s.is_channel||s.isChannel||s.is_shared_chat||s.isSharedChat||pos(s.members_count||s.membersCount)||pos(s.participants_count||s.participantsCount)||pos(s.chat_members_count||s.chatMembersCount));}
function neg(v=''){return /^-\d+$/.test(clean(v));}
function isGroupContext(message={}){const body=message&&typeof message.body==='object'?message.body:{};const r=message&&typeof message.recipient==='object'?message.recipient:(body.recipient||{});const c=message&&typeof message.chat==='object'?message.chat:(body.chat&&typeof body.chat==='object'?body.chat:{});const rt=clean(r.chat_type||r.type).toLowerCase();const mt=clean(message.chat_type||message.chatType||message.type||body.chat_type||body.chatType||body.type).toLowerCase();const ct=clean(c.type||c.chat_type||c.chatType).toLowerCase();const groups=['group','public','channel','supergroup','shared','shared_chat'];const priv=['private','direct','dialog','user','bot'];if(groups.includes(rt)||groups.includes(mt)||groups.includes(ct))return true;const chatId=first(r.chat_id,r.chatId,r.id,message.chat_id,message.chatId,body.chat_id,body.chatId,c.id,c.chat_id,c.chatId);const senderId=first(message?.sender?.user_id,message?.sender?.userId,message?.sender?.id,body?.sender?.user_id,body?.sender?.userId,body?.sender?.id,message?.from?.user_id,message?.from?.userId,message?.from?.id,body?.from?.user_id,body?.from?.userId,body?.from?.id,message?.user?.user_id,message?.user?.userId,message?.user?.id,body?.user?.user_id,body?.user?.userId,body?.user?.id,message?.user_id,message?.userId,body?.user_id,body?.userId);const ru=first(r.user_id,r.userId,r.uid,body?.recipient?.user_id,body?.recipient?.userId,body?.recipient?.id);if(hints(r)||hints(c)||hints(body.chat||{}))return true;if(neg(chatId))return true;if(priv.includes(rt)||priv.includes(mt)||priv.includes(ct))return false;if(ru&&senderId&&ru===senderId)return false;if(rt==='chat'||mt==='chat'||ct==='chat')return Boolean(chatId&&senderId&&chatId!==senderId);return Boolean(chatId&&senderId&&chatId!==senderId);}
function clientGroupHelpScreen(){return{id:'pr185_group_client_help',text:['🔔 Уведомления чата','','Отправьте /push, чтобы подключить уведомления этого чата.','Если нужна помощь, откройте личный чат с ботом.'].join('\n'),attachments:[]};}
function isCommandAllowedInContext({command='',message={}}={}){return !isGroupContext(message)||PUBLIC_GROUP_COMMANDS.includes(command);}
function single({command='',groupContext=false}={}){return !groupContext&&command!=='/clear';}
function strip(message={}){const body=message&&typeof message.body==='object'?message.body:{};const nb={...body};delete nb.mid;delete nb.message_id;delete nb.messageId;delete nb.id;return{...message,body:nb,mid:'',message_id:'',messageId:'',id:'',__adminkitSlashSingleActiveEditTarget:'latest_bot_menu_only'};}
function pr237Contract(){return{...CONTRACT};}
async function cleanup(config,userId,fn,opt={}){if(!fn||!userId)return[];try{return await fn(config,userId,{includeUserMessages:Boolean(opt.includeUserMessages)});}catch(e){trace.log('slash.cleanup_error',{userId,error:e?.message||String(e)});return[];}}
function count(xs){return Array.isArray(xs)?xs.length:0;}
async function screen(args){const{config,message,userId,cleanupAdminWorkspaceOnMainMenu,sendFreshAdminMessage,replyToUser,route='main:home',note='',skipCleanup=false,command='',screen:given=null,useSingleActiveMenu=false,upsertBotMessage=null}=args;if(!skipCleanup)await cleanup(config,userId,cleanupAdminWorkspaceOnMainMenu);const s=given||menuCore.screenForPayload({action:route,route})||menuCore.mainScreen();const text=[note?clean(note):'',s.text||'АдминКИТ'].filter(Boolean).join('\n\n');const attachments=Array.isArray(s.attachments)?s.attachments:[];if(useSingleActiveMenu&&typeof upsertBotMessage==='function')return upsertBotMessage({config,message:strip(message),text,attachments,editCurrent:true});const send=sendFreshAdminMessage||replyToUser;return send({config,message,text,attachments});}
async function handleNativeSlashCommand({config,message,command,helpers}){const{getSenderUserId,replyToUser,sendFreshAdminMessage,cleanupAdminWorkspaceOnMainMenu,upsertBotMessage}=helpers;const userId=getSenderUserId(message);const groupContext=isGroupContext(message);if(!isCommandAllowedInContext({command,message,userId}))return screen({config,message,userId,cleanupAdminWorkspaceOnMainMenu,sendFreshAdminMessage,replyToUser,route:'help:home',skipCleanup:true,command,screen:clientGroupHelpScreen()});if(groupContext&&command==='/push')return false;if(groupContext&&command==='/help')return screen({config,message,userId,cleanupAdminWorkspaceOnMainMenu,sendFreshAdminMessage,replyToUser,route:'help:home',skipCleanup:true,command,screen:clientGroupHelpScreen()});if(command==='/clear'){const failed=await cleanup(config,userId,cleanupAdminWorkspaceOnMainMenu,{includeUserMessages:true});return screen({config,message,userId,cleanupAdminWorkspaceOnMainMenu,sendFreshAdminMessage,replyToUser,route:'main:home',skipCleanup:true,command,screen:account.gateMenuForUser(userId),note:count(failed)?'Чат очищен частично. Открываю актуальный экран.':'Чат очищен от активных меню бота. Открываю актуальный экран.'});}const route=ROUTES[command];if(!route)return false;let given=null;let note=command==='/menu'||command==='/start'?'Главное меню открыто.':'';if(command==='/account')given=account.accountHome(userId);else if(command==='/start'||command==='/menu')given=account.gateMenuForUser(userId);else{const d=gate.checkCommand(userId,command);if(!d.allow)given=account.screenForGateDecision(d,userId);else if(command==='/debug'&&access.isAdmin(userId))given=menuCore.screenForPayload({action:'admin_section_debug'});}const use=single({command,groupContext});return screen({config,message,userId,cleanupAdminWorkspaceOnMainMenu,sendFreshAdminMessage,replyToUser,route,command,screen:given,note,skipCleanup:use,useSingleActiveMenu:use,upsertBotMessage});}
module.exports={PUBLIC_GROUP_COMMANDS,ADMIN_PRIVATE_COMMANDS,getNativeSlashCommand,isGroupContext,isCommandAllowedInContext,clientGroupHelpScreen,pr237Contract,handleNativeSlashCommand};
