'use strict';

const https = require('https');
const liveIdentity = require('./liveIdentityService');
const startupLogService = require('./startupLogService');

const DEFAULT_REPO = startupLogService.DEFAULT_REPO || '9163223-maker/amio-comments-max';
const DEFAULT_BRANCH = 'runtime-status';
const ROOT_MENU_DEFAULT_PATH = 'runtime/root-menu-live-parity-trace.json';
const MANUAL_DEFAULT_PATH = 'runtime/manual-ui-walkthrough-trace.json';
const DEFAULT_LIMIT = 100;
const USER_AGENT = 'adminkit-pr247-root-menu-live-parity-trace';

const ROOT_ROUTES = new Set(['channels:home','comments:home','gifts:home','buttons:home','stats:home','push:home','ad_links:home','polls:home','highlights:home','editor:home','archive:home','account:home','settings:home','main:home']);
const LEGACY_ROOT_ACTION_ROUTES = { admin_section_channels:'channels:home', admin_section_comments:'comments:home', admin_section_gifts:'gifts:home', gift_admin_open_menu:'gifts:home', admin_section_buttons:'buttons:home', admin_section_stats:'stats:home', admin_section_push:'push:home', admin_section_polls:'polls:home', admin_section_posts:'editor:home', admin_section_archive:'archive:home', admin_section_tariffs:'account:home', admin_section_main:'main:home' };
const V3_OWNERS = new Set(['main','channels','comments','gifts','buttons','stats','push','ad_links','polls','highlights','editor','archive','account','settings','terms','privacy']);

function state() { if (!global.__ADMINKIT_PR247_TRACE__) global.__ADMINKIT_PR247_TRACE__ = { seq: 0, rootEvents: [], manualEvents: [], rootStatus: status(ROOT_MENU_DEFAULT_PATH), manualStatus: status(MANUAL_DEFAULT_PATH), exporter: null }; return global.__ADMINKIT_PR247_TRACE__; }
function clean(v) { return String(v || '').trim(); }
function short(v, n = 160) { return clean(v).slice(0, n); }
function nowIso() { return new Date().toISOString(); }
function limit() { const n = Number(process.env.ADMINKIT_PR247_TRACE_LIMIT || DEFAULT_LIMIT); return Number.isFinite(n) && n > 0 ? Math.min(Math.max(Math.floor(n), 50), 120) : DEFAULT_LIMIT; }
function status(path) { return { attempted: false, targetBranch: DEFAULT_BRANCH, targetPath: path, ok: false, reasonCategory: 'no_events', lastAttemptAt: '', lastSuccessAt: '', errorMessage: '' }; }
function categorize(error) { const msg = clean(error && (error.code || error.status || error.message || error)); if (!clean(process.env.GITHUB_DEBUG_TOKEN)) return 'missing_token'; if (/disabled/i.test(msg)) return 'disabled'; if (/no_events/i.test(msg)) return 'no_events'; if (/github|status|timeout|404|401|403|422|500/i.test(msg)) return 'github_api_error'; return 'unexpected_error'; }
function safeError(error) { return short(clean(error && (error.code || error.status || error.message) || error).replace(/ghp_[A-Za-z0-9_]+|github_pat_[A-Za-z0-9_]+|Bearer\s+\S+/gi, '[redacted]'), 160); }
function safeStr(v, n = 120) { let s = clean(v); s = s.replace(/https?:\/\/[^\s]*\/push\/join\?t=[^\s]+/gi, '[push-join-url-redacted]'); s = s.replace(/https?:\/\/clck\.ru\/[^\s]+/gi, '[clck-url-redacted]'); s = s.replace(/([?&])(?:access_token|token|authorization|secret|password|api[_-]?key|endpoint|auth|p256dh|vapid|private[_-]?key)=([^\s&#]+)/gi, '$1[redacted-query-field]=[redacted]'); s = s.replace(/([\"'])(?:token|authorization|secret|password|apiKey|accessToken|refreshToken|commentKey|callbackId|userId|chatId|messageId|channelId|postId|url)\1\s*:\s*([\"'])(?:\\.|(?!\2).)*\2/gi, '$1[redacted-key]$1:$2[redacted]$2'); s = s.replace(/\b(?:access_token|token|authorization|secret|password|api[_-]?key|endpoint|auth|p256dh|vapid|private[_-]?key)=([^\s&]+)/gi, (m) => m.replace(/=.*/, '=[redacted]')); return short(s.replace(/[\r\n\t]+/g, ' ').replace(/\s+/g, ' '), n); }
function runtimeIdentity(extra = {}) { const id = liveIdentity.fingerprint ? liveIdentity.fingerprint() : {}; return { deployStartedAt: id.serverStartedAt || '', githubMainHeadSha: id.gitCommit || id.runtimeGitCommit || '', runtimeVersion: id.runtimeVersion || process.env.RUNTIME_VERSION || process.env.BUILD_VERSION || 'unknown', sourceMarker: id.sourceMarker || process.env.BUILD_SOURCE_MARKER || '', ...extra.runtimeIdentity }; }
function parseMaybeJson(value) { if (!clean(value)) return null; if (typeof value !== 'string') return value && typeof value === 'object' ? value : null; try { const parsed = JSON.parse(value); return parsed && typeof parsed === 'object' ? parsed : null; } catch { return null; } }
function pickCallbackBody(body = {}) { if (!body || typeof body !== 'object') return null; if (body.callback && typeof body.callback === 'object') return body.callback; if (body.data && body.data.callback && typeof body.data.callback === 'object') return body.data.callback; return null; }
function pickMessageBody(body = {}, cb = null) { return body.message || (body.data && body.data.message) || (cb && cb.message) || null; }
function normalizePayload(input = {}) { const cb = input.callback || pickCallbackBody(input.body || {}); const raw = input.payload !== undefined ? input.payload : cb && (cb.payload ?? cb.data); const obj = raw && typeof raw === 'object' ? raw : parseMaybeJson(raw); const shape = raw === undefined || raw === null || raw === '' ? 'missing' : (obj ? 'object' : typeof raw === 'string' ? 'plain_string' : typeof raw); return { raw, obj, shape }; }
function payloadKeys(obj) { return obj && typeof obj === 'object' && !Array.isArray(obj) ? Object.keys(obj).slice(0, 24).map((k) => /token|authorization|secret|password|api[_-]?key|accessToken|refreshToken|commentKey|callbackId|userId|chatId|messageId|channelId|postId|url/i.test(k) ? '[redacted-key]' : safeStr(k, 60)) : []; }
function isV3(route) { const r = clean(route); return /^[a-z][a-z0-9_]*:[a-z0-9_]+$/i.test(r) && V3_OWNERS.has(r.split(':')[0]); }
function resolveRoot(obj = {}) { const route = clean(obj.route); if (ROOT_ROUTES.has(route)) return { route, resolver: 'payload.route' }; const r = clean(obj.r); if (ROOT_ROUTES.has(r)) return { route: r, resolver: 'payload.r' }; const action = clean(obj.action); if (ROOT_ROUTES.has(action)) return { route: action, resolver: 'payload.action.canonical' }; if (LEGACY_ROOT_ACTION_ROUTES[action]) return { route: LEGACY_ROOT_ACTION_ROUTES[action], resolver: 'legacy.compatibility', legacyAction: action }; return { route: '', resolver: '' }; }
function resolveV3(obj = {}) { const route = clean(obj.route); if (isV3(route)) return { route, resolver: 'payload.route' }; const r = clean(obj.r); if (isV3(r)) return { route: r, resolver: 'payload.r' }; const action = clean(obj.action); if (isV3(action)) return { route: action, resolver: 'payload.action.canonical' }; return { route: '', resolver: '' }; }
function hasId(obj = {}, names = []) { return names.some((n) => clean(obj && obj[n])); }
function buildEvent(input = {}) { const body = input.body || (input.req && input.req.body) || {}; const cb = input.callback || pickCallbackBody(body); const msg = input.message || pickMessageBody(body, cb); const p = normalizePayload({ ...input, body, callback: cb }); const obj = p.obj || {}; const root = resolveRoot(obj); const v3 = resolveV3(obj); const id = runtimeIdentity(input); const action = safeStr(obj.action || (typeof p.raw === 'string' && !p.obj ? p.raw : ''), 120); const route = safeStr(obj.route, 120); const r = safeStr(obj.r, 120); return { seq: ++state().seq, at: input.at || nowIso(), deployStartedAt: id.deployStartedAt, githubMainHeadSha: id.githubMainHeadSha, runtimeVersion: id.runtimeVersion, sourceMarker: id.sourceMarker, updateType: safeStr(input.updateType || body.update_type || body.updateType || body.type, 80), eventKind: safeStr(input.eventKind || input.kind || 'callback_received', 80), callbackAction: action, callbackRoute: route, callbackR: r, canonicalAction: safeStr(input.canonicalAction || obj.canonicalAction || (isV3(action) ? action : ''), 120), legacyAction: safeStr(input.legacyAction || obj.legacyAction || root.legacyAction || '', 120), source: safeStr(input.source || obj.source || '', 80), payloadKeys: payloadKeys(obj), payloadShape: p.shape, hasCallback: Boolean(cb || input.hasCallback), hasMessage: Boolean(msg || input.hasMessage), hasUserId: Boolean(input.hasUserId || hasId(cb && (cb.user || cb.sender || cb.from) || {}, ['user_id','userId','id']) || hasId(body, ['user_id','userId'])), hasCallbackId: Boolean(input.hasCallbackId || hasId(cb || {}, ['callback_id','callbackId','id'])), messagePresentSource: msg ? safeStr(input.messagePresentSource || (cb && cb.message ? 'callback.message' : 'body.message'), 80) : '', textPreview: safeStr(input.textPreview || input.buttonPreview || obj.text || obj.label || (typeof p.raw === 'string' ? p.raw : JSON.stringify(obj || {})), 160), buttonPreview: safeStr(input.buttonPreview || obj.buttonText || obj.text || '', 120), rootSectionCandidate: Boolean(root.route), resolvedRootRoute: safeStr(input.resolvedRootRoute || root.route, 120), resolvedV3Route: safeStr(input.resolvedV3Route || v3.route, 120), resolver: safeStr(input.resolver || root.resolver || v3.resolver, 120), handlerName: safeStr(input.handlerName || '', 120), dedupeDecision: safeStr(input.dedupeDecision || '', 80), resultKind: safeStr(input.resultKind || '', 120), delivery: safeStr(input.delivery || '', 120), errorCode: safeStr(input.errorCode || input.error || '', 120), status: safeStr(input.status || '', 120), totalMs: Number.isFinite(Number(input.totalMs)) ? Number(input.totalMs) : undefined, renderMs: Number.isFinite(Number(input.renderMs)) ? Number(input.renderMs) : undefined, deliveryMs: Number.isFinite(Number(input.deliveryMs)) ? Number(input.deliveryMs) : undefined, traceExportStatus: input.traceExportStatus || undefined } };
function compact(e) { return Object.fromEntries(Object.entries(e).filter(([,v]) => v !== undefined)); }

function markExportUnavailable(reasonCategory = 'missing_token') {
  try {
    const st = state();
    const at = nowIso();
    const safeReason = safeStr(reasonCategory || 'missing_token', 80) || 'missing_token';
    for (const [kind, stat] of [['root', st.rootStatus], ['manual', st.manualStatus]]) {
      stat.attempted = true;
      stat.targetBranch = DEFAULT_BRANCH;
      stat.targetPath = kind === 'root' ? ROOT_MENU_DEFAULT_PATH : MANUAL_DEFAULT_PATH;
      stat.ok = false;
      stat.reasonCategory = safeReason;
      stat.lastAttemptAt = at;
      stat.errorMessage = safeReason === 'missing_token' ? 'GITHUB_DEBUG_TOKEN missing' : safeReason;
    }
  } catch {}
}

function record(input = {}) { try { const st = state(); const ev = compact(buildEvent(input)); st.manualEvents.push(ev); if (ev.rootSectionCandidate || ev.resolvedRootRoute || ev.legacyAction) st.rootEvents.push({ ...ev }); const cap = limit(); if (st.manualEvents.length > cap) st.manualEvents.splice(0, st.manualEvents.length - cap); if (st.rootEvents.length > cap) st.rootEvents.splice(0, st.rootEvents.length - cap); if (clean(process.env.GITHUB_DEBUG_TOKEN)) exportTraces({ reason: input.eventKind || 'event' }).catch(() => {}); else markExportUnavailable('missing_token'); return ev; } catch { return null; } }
function summary(events = []) { const byRoute = {}; for (const e of events) { const k = e.resolvedRootRoute || e.callbackRoute || e.callbackAction || 'unknown'; if (!byRoute[k]) byRoute[k] = { route: k, count: 0, lastSeq: 0, lastAt: '', lastResultKind: '', lastDelivery: '', lastErrorCode: '' }; byRoute[k].count += 1; byRoute[k].lastSeq = e.seq; byRoute[k].lastAt = e.at; byRoute[k].lastResultKind = e.resultKind || byRoute[k].lastResultKind; byRoute[k].lastDelivery = e.delivery || byRoute[k].lastDelivery; byRoute[k].lastErrorCode = e.errorCode || byRoute[k].lastErrorCode; } return Object.values(byRoute).sort((a,b)=>b.lastSeq-a.lastSeq); }
function payload(kind='manual') { const st = state(); const events = (kind === 'root' ? st.rootEvents : st.manualEvents).slice(-limit()); const path = kind === 'root' ? ROOT_MENU_DEFAULT_PATH : MANUAL_DEFAULT_PATH; return { ok: true, updatedAt: nowIso(), limit: limit(), latestRuntimeIdentity: runtimeIdentity(), summary: summary(events), events, safe: true, traceExportStatus: kind === 'root' ? st.rootStatus : st.manualStatus, targetBranch: DEFAULT_BRANCH, targetPath: path }; }

function appendTraceExportEvent(kind, result = {}) {
  try {
    const st = state();
    const path = kind === 'root' ? ROOT_MENU_DEFAULT_PATH : MANUAL_DEFAULT_PATH;
    const id = runtimeIdentity();
    const ev = compact({ seq: ++st.seq, at: nowIso(), deployStartedAt: id.deployStartedAt, githubMainHeadSha: id.githubMainHeadSha, runtimeVersion: id.runtimeVersion, sourceMarker: id.sourceMarker, updateType: 'trace_export', eventKind: result.eventKind || 'trace_export_attempted', resultKind: result.ok ? 'trace_export_succeeded' : (result.resultKind || 'trace_export_attempted'), delivery: DEFAULT_BRANCH, errorCode: safeStr(result.errorCode || result.reasonCategory || '', 120), status: safeStr(result.status || path, 160), hasCallback: false, hasMessage: false, hasUserId: false, hasCallbackId: false, payloadKeys: [], payloadShape: 'trace_export', rootSectionCandidate: false, traceExportStatus: kind === 'root' ? st.rootStatus : st.manualStatus });
    st.manualEvents.push(ev);
    if (kind === 'root') st.rootEvents.push({ ...ev });
    const cap = limit();
    if (st.manualEvents.length > cap) st.manualEvents.splice(0, st.manualEvents.length - cap);
    if (st.rootEvents.length > cap) st.rootEvents.splice(0, st.rootEvents.length - cap);
  } catch {}
}

function b64(v){return Buffer.from(String(v||''),'utf8').toString('base64');} function fromB64(v){return Buffer.from(String(v||''),'base64').toString('utf8');}
function requestJson({ method='GET', path, token, body }) { return new Promise((resolve,reject)=>{ const data = body === undefined ? null : JSON.stringify(body); const req = https.request({ hostname:'api.github.com', method, path, headers:{ 'User-Agent':USER_AGENT, Accept:'application/vnd.github+json', Authorization:`Bearer ${token}`, ...(data?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}:{}) } }, res=>{ let raw=''; res.setEncoding('utf8'); res.on('data',c=>raw+=c); res.on('end',()=>{ let json=null; try{json=raw?JSON.parse(raw):null;}catch{json={raw};} if(res.statusCode>=200&&res.statusCode<300)return resolve(json); const err=new Error(json&&json.message||`github_status_${res.statusCode}`); err.status=res.statusCode; reject(err); }); }); req.on('error',reject); req.setTimeout(8000,()=>req.destroy(new Error('github_timeout'))); if(data)req.write(data); req.end(); }); }
async function readFile({repo,branch,path,token}){ try{ const f=await requestJson({path:`/repos/${repo}/contents/${encodeURIComponent(path).replace(/%2F/g,'/')}?ref=${encodeURIComponent(branch)}`,token}); return {sha:f.sha}; } catch(e){ if(e.status===404)return {sha:''}; throw e; } }
async function writeOne(kind) { const st=state(); const token=clean(process.env.GITHUB_DEBUG_TOKEN); const stat = kind === 'root' ? st.rootStatus : st.manualStatus; const path = kind === 'root' ? ROOT_MENU_DEFAULT_PATH : MANUAL_DEFAULT_PATH; stat.attempted = true; stat.lastAttemptAt = nowIso(); stat.targetBranch = DEFAULT_BRANCH; stat.targetPath = path; if(!token) throw new Error('missing_token'); const repo=DEFAULT_REPO; await (startupLogService.ensureBranch ? startupLogService.ensureBranch({repo,branch:DEFAULT_BRANCH,token}) : Promise.resolve()); const cur=await readFile({repo,branch:DEFAULT_BRANCH,path,token}); const log=payload(kind); await requestJson({ method:'PUT', path:`/repos/${repo}/contents/${encodeURIComponent(path).replace(/%2F/g,'/')}`, token, body:{ message:`PR247 trace ${kind} ${log.latestRuntimeIdentity.runtimeVersion || 'runtime'}`, content:b64(`${JSON.stringify(log,null,2)}\n`), branch:DEFAULT_BRANCH, ...(cur.sha?{sha:cur.sha}:{}) } }); stat.ok=true; stat.reasonCategory=''; stat.errorMessage=''; stat.lastSuccessAt=nowIso(); return { ok:true, branch:DEFAULT_BRANCH, path } }
async function exportTraces() { const st=state(); const out=[]; for (const kind of ['root','manual']) { const stat = kind === 'root' ? st.rootStatus : st.manualStatus; appendTraceExportEvent(kind, { eventKind: 'trace_export_attempted', resultKind: 'trace_export_attempted' }); try { if ((kind === 'root' ? st.rootEvents : st.manualEvents).length < 1) throw new Error('no_events'); out.push(await (st.exporter ? st.exporter(kind, payload(kind)) : writeOne(kind))); stat.ok = true; stat.lastSuccessAt = nowIso(); appendTraceExportEvent(kind, { ok: true, eventKind: 'trace_export_succeeded' }); } catch(e) { stat.attempted = true; stat.lastAttemptAt = nowIso(); stat.ok = false; stat.reasonCategory = categorize(e); stat.errorMessage = safeError(e); appendTraceExportEvent(kind, { ok: false, eventKind: 'trace_export_failed', reasonCategory: stat.reasonCategory }); out.push({ ok:false, kind, reasonCategory: stat.reasonCategory, error: stat.errorMessage }); } } return out; }
function clear(){ const st=state(); st.seq=0; st.rootEvents=[]; st.manualEvents=[]; st.rootStatus=status(ROOT_MENU_DEFAULT_PATH); st.manualStatus=status(MANUAL_DEFAULT_PATH); st.exporter=null; }
function _setExporterForTests(fn){ state().exporter = typeof fn === 'function' ? fn : null; }
module.exports = { DEFAULT_BRANCH, ROOT_MENU_DEFAULT_PATH, MANUAL_DEFAULT_PATH, DEFAULT_LIMIT, ROOT_ROUTES, LEGACY_ROOT_ACTION_ROUTES, record, payload, listRoot:()=>state().rootEvents.slice(), listManual:()=>state().manualEvents.slice(), summary, exportTraces, clear, _setExporterForTests, extractSafePayload: (input)=>buildEvent(input) };
