'use strict';

const https = require('https');
const startupLogService = require('./startupLogService');

const DEFAULT_BRANCH = 'runtime-status';
const ROOT_PARITY_DEFAULT_PATH = 'runtime/root-menu-live-parity-trace.json';
const MANUAL_WALKTHROUGH_DEFAULT_PATH = 'runtime/manual-ui-walkthrough-trace.json';
const DEFAULT_LIMIT = 100;
const USER_AGENT = 'adminkit-root-menu-parity-pr246';
const ROOT_ROUTES = new Set(['main:home','channels:home','comments:home','gifts:home','buttons:home','stats:home','push:home','ad_links:home','polls:home','highlights:home','editor:home','archive:home','account:home','settings:home']);
const LEGACY = {admin_section_main:'main:home',admin_section_channels:'channels:home',admin_section_comments:'comments:home',admin_section_gifts:'gifts:home',gift_admin_open_menu:'gifts:home',admin_section_buttons:'buttons:home',admin_section_stats:'stats:home',admin_section_push:'push:home',admin_section_ad_links:'ad_links:home',admin_section_polls:'polls:home',admin_section_highlights:'highlights:home',admin_section_editor:'editor:home',admin_section_archive:'archive:home',admin_section_account:'account:home',admin_section_settings:'settings:home'};
const WALK_TYPES = new Set(['webhook_edge_received','callback_received','root_resolved','v3_resolved','legacy_compatibility_resolved','duplicate_skipped','unsupported_callback','render_started','render_resolved','delivery_started','delivery_resolved','delivery_failed','handler_returned','trace_export_attempted','trace_export_succeeded','trace_export_failed']);
const state = { seq:0, parityEvents:[], walkEvents:[], exportStatus:{}, timer:null, inFlight:false, exporter:null };
function clean(v){return String(v==null?'':v).trim();}
function now(){return new Date().toISOString();}
function runtime(){return clean(process.env.RUNTIME_VERSION||process.env.BUILD_VERSION)||'unknown';}
function source(){return clean(process.env.BUILD_SOURCE_MARKER||process.env.SOURCE_MARKER||process.env.npm_package_sourceMarker)||'';}
function short(v,n=160){return clean(v).replace(/ghp_[A-Za-z0-9_]+|github_pat_[A-Za-z0-9_]+|Bearer\s+\S+|token=[^\s&]+/gi,'[redacted]').slice(0,n);}
function identity(){return {deployStartedAt:clean(process.env.DEPLOY_STARTED_AT||process.env.STARTED_AT),githubMainHeadSha:clean(process.env.GITHUB_MAIN_HEAD_SHA||process.env.GITHUB_SHA),runtimeVersion:runtime(),sourceMarker:source()};}
function limit(){const n=Number(process.env.ADMINKIT_PR246_TRACE_LIMIT||DEFAULT_LIMIT);return Number.isFinite(n)&&n>0?Math.min(Math.max(Math.floor(n),20),120):DEFAULT_LIMIT;}
function isSensitiveKey(k){return /token|secret|authorization|cookie|password|session|commentKey|callbackId|callback_id|userId|user_id|chatId|chat_id|messageId|message_id|channelId|channel_id|postId|post_id|mid|url|link/i.test(clean(k));}
function parsePayload(input){let v=input;if(input&&typeof input==='object'&&('payload'in input||'callback_data'in input||'callbackData'in input))v=input.payload??input.callback_data??input.callbackData;if(v&&typeof v==='object')return {payload:v,shape:Object.keys(v).length?'object':'missing'};const s=clean(v);if(!s)return {payload:{},shape:'missing'};try{const o=JSON.parse(s);return o&&typeof o==='object'?{payload:o,shape:'json_string'}:{payload:{action:s,raw:s},shape:'plain_string'};}catch{return {payload:{action:s,raw:s},shape:'plain_string'};}}
function safePayloadMetadata(input={}){const parsed=parsePayload(input);const p=parsed.payload||{};const keys=Object.keys(p).filter(k=>!isSensitiveKey(k)).sort();const safe={};for(const k of keys){const val=p[k];if(['action','route','r','canonicalAction','legacyAction','source'].includes(k))safe[k]=short(val,80);}
const action=short(p.action||safe.action,80), route=short(p.route||safe.route,80), r=short(p.r||safe.r,80);return {callbackAction:action,callbackRoute:route,callbackR:r,canonicalAction:short(p.canonicalAction||'',80),legacyAction:short(p.legacyAction||'',80),source:short(p.source||'',80),payloadKeys:keys,payloadShape:parsed.shape,rootSectionCandidate:ROOT_ROUTES.has(route||r||action)||Boolean(LEGACY[action]),resolvedRootRoute:ROOT_ROUTES.has(route||r||action)?(route||r||action):(LEGACY[action]||''),...safe};}
function sanitize(input={}){const meta=safePayloadMetadata(input.payload||input);const out={seq:++state.seq,at:now(),...identity(),updateType:short(input.updateType||input.update_type||input.type||'',80),...meta,hasCallback:Boolean(input.hasCallback),hasMessage:Boolean(input.hasMessage),hasUserId:Boolean(input.hasUserId),hasCallbackId:Boolean(input.hasCallbackId),messagePresentSource:short(input.messagePresentSource||'',80),textPreview:short(input.textPreview||input.buttonPreview||input.text||'',120),resolver:short(input.resolver||'',80),handlerName:short(input.handlerName||input.handledBy||'',100),dedupeDecision:short(input.dedupeDecision||input.duplicateReason||'',80),resultKind:short(input.resultKind||input.reason||input.type||'',80),delivery:short(input.delivery||'',80),errorCode:short(input.errorCode||input.error||'',80),status:short(input.status||'',160),totalMs:Number.isFinite(Number(input.totalMs))?Number(input.totalMs):undefined,renderMs:Number.isFinite(Number(input.renderMs))?Number(input.renderMs):undefined,deliveryMs:Number.isFinite(Number(input.deliveryMs))?Number(input.deliveryMs):undefined,traceExportStatus:exportStatusSummary()};return Object.fromEntries(Object.entries(out).filter(([,v])=>v!==undefined&&v!==''));}
function push(arr,e){arr.push(e);const cap=limit();if(arr.length>cap)arr.splice(0,arr.length-cap);}
function eventKindFromAudit(type){return type==='callback_received_pre_dedupe'?'callback_received':type==='root_section_callback_received'?'root_resolved':type==='root_section_callback_resolved'?'delivery_resolved':type==='root_section_callback_failed'?'delivery_failed':type==='v3_route_callback_received'?'v3_resolved':type==='v3_route_callback_resolved'?'delivery_resolved':type==='v3_route_callback_failed'?'delivery_failed':type==='duplicate_callback_skipped'?'duplicate_skipped':type==='unsupported_callback'?'unsupported_callback':'handler_returned';}
function record(kind,input={}){try{const e=sanitize(input);e.eventKind=WALK_TYPES.has(kind)?kind:eventKindFromAudit(kind);if(input.route&&!e.resolvedRootRoute&&ROOT_ROUTES.has(clean(input.route)))e.resolvedRootRoute=clean(input.route);if(input.route&&!e.resolvedV3Route&&!ROOT_ROUTES.has(clean(input.route)))e.resolvedV3Route=clean(input.route);if(/^admin_section_|^gift_admin_open_menu$/.test(e.callbackAction||input.action||''))e.resolver=e.resolver||'legacy_compatibility'; if(e.resolver==='legacy_compatibility')e.eventKind='legacy_compatibility_resolved';push(state.walkEvents,e);if(e.rootSectionCandidate||e.resolvedRootRoute||ROOT_ROUTES.has(clean(input.route))||/^admin_section_/.test(clean(input.action)))push(state.parityEvents,e);scheduleExport({reason:'record'});return e;}catch{return null;}}
function ingestAuditEvent(type,payload={}){return record(type,{...payload,payload});}
function exportStatusSummary(path){const s=state.exportStatus[path||'last']||{};return {attempted:!!s.lastAttemptAt,targetBranch:DEFAULT_BRANCH,targetPath:s.path||path||'',success:!!s.lastSuccessAt&&s.ok!==false,failureReasonCategory:s.failureReasonCategory||'',lastAttemptAt:s.lastAttemptAt||'',lastSuccessAt:s.lastSuccessAt||'',errorMessage:s.errorMessage||''};}
function summary(events){const m={};for(const e of events){const k=e.resolvedRootRoute||e.callbackRoute||e.callbackAction||'unknown';m[k]=m[k]||{route:k,count:0,lastSeq:0,lastAt:''};m[k].count++;m[k].lastSeq=e.seq;m[k].lastAt=e.at;}return Object.values(m).sort((a,b)=>b.lastSeq-a.lastSeq);}
function payloadFor(path,events){return {ok:true,updatedAt:now(),limit:limit(),latestRuntimeIdentity:identity(),summary:summary(events),traceExportStatus:exportStatusSummary(path),events:events.slice(),safe:true};}
function b64(v){return Buffer.from(String(v),'utf8').toString('base64');}
function fromB64(v){return Buffer.from(String(v||''),'base64').toString('utf8');}
function reqJson({method='GET',repo,path,token,body}){return new Promise((resolve,reject)=>{const data=body?JSON.stringify(body):null;const req=https.request({hostname:'api.github.com',method,path,headers:{'User-Agent':USER_AGENT,Accept:'application/vnd.github+json',Authorization:`Bearer ${token}`,...(data?{'Content-Type':'application/json','Content-Length':Buffer.byteLength(data)}:{})}},res=>{let raw='';res.setEncoding('utf8');res.on('data',c=>raw+=c);res.on('end',()=>{let j=null;try{j=raw?JSON.parse(raw):null;}catch{j={raw};}if(res.statusCode>=200&&res.statusCode<300)return resolve(j);const er=new Error(j&&j.message||`github_status_${res.statusCode}`);er.status=res.statusCode;reject(er);});});req.on('error',reject);req.setTimeout(8000,()=>req.destroy(new Error('github_timeout')));if(data)req.write(data);req.end();});}
async function writeGithub(path,log){const token=clean(process.env.GITHUB_DEBUG_TOKEN);if(!token){const e=new Error('GITHUB_DEBUG_TOKEN not configured');e.category='missing_token';throw e;}const repo=startupLogService.DEFAULT_REPO||'9163223-maker/amio-comments-max';await (startupLogService.ensureBranch?startupLogService.ensureBranch({repo,branch:DEFAULT_BRANCH,token}):Promise.resolve());let sha='';try{const f=await reqJson({repo,token,path:`/repos/${repo}/contents/${encodeURIComponent(path).replace(/%2F/g,'/')}?ref=${encodeURIComponent(DEFAULT_BRANCH)}`});sha=f.sha||'';}catch(e){if(e.status!==404)throw e;}return reqJson({method:'PUT',repo,token,path:`/repos/${repo}/contents/${encodeURIComponent(path).replace(/%2F/g,'/')}`,body:{message:`PR246 trace ${path}`,content:b64(JSON.stringify(log,null,2)+'\n'),branch:DEFAULT_BRANCH,...(sha?{sha}:{})}});}
function cat(e){return e&&e.category?e.category:e&&e.status?'github_api_error':/token/i.test(String(e&&e.message||''))?'missing_token':'unexpected_error';}
async function exportOne(path,events){const s=state.exportStatus[path]={path,lastAttemptAt:now(),ok:false,failureReasonCategory:'',errorMessage:'',lastSuccessAt:(state.exportStatus[path]||{}).lastSuccessAt||''};record('trace_export_attempted',{payload:{action:'trace_export',route:''},resultKind:'trace_export_attempted'});try{if(!events.length){s.failureReasonCategory='no_events';return {ok:false,skipped:true,reason:'no_events'};}const log=payloadFor(path,events);const exporter=state.exporter||writeGithub;await exporter(path,log);s.ok=true;s.lastSuccessAt=now();record('trace_export_succeeded',{payload:{action:'trace_export'},resultKind:'trace_export_succeeded'});return {ok:true,branch:DEFAULT_BRANCH,path};}catch(e){s.ok=false;s.failureReasonCategory=cat(e);s.errorMessage=short(e&&e.message||e,160);record('trace_export_failed',{payload:{action:'trace_export'},resultKind:'trace_export_failed',error:s.failureReasonCategory,status:s.errorMessage});return {ok:false,error:s.errorMessage,category:s.failureReasonCategory};}}
async function exportLatestTrace(){if(state.inFlight)return {ok:true,skipped:true,reason:'in_flight'};state.inFlight=true;try{const a=await exportOne(ROOT_PARITY_DEFAULT_PATH,state.parityEvents);const b=await exportOne(MANUAL_WALKTHROUGH_DEFAULT_PATH,state.walkEvents);return {ok:a.ok&&b.ok,root:a,manual:b};}finally{state.inFlight=false;}}
function scheduleExport(){if(process.env.ADMINKIT_TEST_MODE==='1')return {ok:true,scheduled:false,testMode:true};if(state.timer)clearTimeout(state.timer);state.timer=setTimeout(()=>exportLatestTrace().catch(()=>{}),1500);if(state.timer.unref)state.timer.unref();return {ok:true,scheduled:true};}
function clear(){state.seq=0;state.parityEvents=[];state.walkEvents=[];state.exportStatus={};if(state.timer)clearTimeout(state.timer);state.timer=null;}
function info(){return {ok:true,limit:limit(),root:payloadFor(ROOT_PARITY_DEFAULT_PATH,state.parityEvents),manual:payloadFor(MANUAL_WALKTHROUGH_DEFAULT_PATH,state.walkEvents)};}
function _setExporterForTests(fn){state.exporter=typeof fn==='function'?fn:null;}
module.exports={DEFAULT_BRANCH,ROOT_PARITY_DEFAULT_PATH,MANUAL_WALKTHROUGH_DEFAULT_PATH,DEFAULT_LIMIT,ROOT_ROUTES,safePayloadMetadata,record,ingestAuditEvent,exportLatestTrace,scheduleExport,info,clear,_setExporterForTests,limit};
