'use strict';
const store = require('../store');
const tenantScope = require('../tenant-scope');
const clientAccessService = require('./clientAccessService');
const pushConnectedChatsService = require('./pushConnectedChatsService');
function clean(v){return String(v||'').replace(/\s+/g,' ').trim();}
function arr(v){return Array.isArray(v)?v:[];}
function visibleName(x, fallback){const s=clean(x.title||x.channelTitle||x.chatTitle||x.name||x.displayName);return s && !/^-?\d{5,}$/.test(s) ? s : fallback;}
function ownerFields(x={}){return [x.ownerUserId,x.linkedByUserId,x.userId,x.maxUserId,x.createdByUserId,x.adminId,x.updatedByUserId].map(clean).filter(Boolean);}
function tenantForUser(userId){try{return clean(tenantScope.ensureTenantContext(clean(userId)).tenantKey);}catch{return '';}}
function channelPostBoundToUser(channelId,userId){return arr(store.getPostsList&&store.getPostsList()).some(p=>clean(p.channelId)===clean(channelId)&&ownerFields(p).includes(clean(userId)));}
function boundToUser(x,userId,channelId=''){const uid=clean(userId); if(!uid)return false; if(ownerFields(x).includes(uid))return true; const tenant=tenantForUser(uid); if(tenant&&clean(x.tenantKey)===tenant)return true; if(channelId&&channelPostBoundToUser(channelId,uid))return true; return false;}
function channelTarget(c,provider){const id=clean(c.channelId||c.id);return {targetKind:'channel',targetId:id,channelId:id,chatId:'',title:visibleName(c,'Канал без названия'),provider};}
function accessChannelsForUser(userId){try{return arr(clientAccessService.getClientChannels&&clientAccessService.getClientChannels(clean(userId)));}catch{return []}}
function listChannels(userId){const seen=new Set();const out=[];const add=(c,provider,requireStoreBinding)=>{const id=clean(c.channelId||c.id); if(!id||seen.has(id))return; if(requireStoreBinding&&!boundToUser(c,userId,id))return; seen.add(id); out.push(channelTarget(c,provider));}; arr(store.getChannelsList&&store.getChannelsList()).forEach(c=>add(c,'channel_registry',true)); accessChannelsForUser(userId).forEach(c=>add(c,'client_access',false)); return out;}
function chatTarget(c,provider){const id=clean(c.chatId||c.id||c.requiredChatId);return {targetKind:'chat',targetId:id,channelId:'',chatId:id,title:visibleName(c,'Чат без названия'),provider};}
function chatAdder(userId){const providers=[]; const out=[]; const seen=new Set(); const add=(c,provider,requireBinding=true)=>{const id=clean(c.chatId||c.id||c.requiredChatId); if(!id||seen.has(id))return; if(requireBinding&&!boundToUser(c,userId,''))return; seen.add(id); out.push(chatTarget(c,provider));}; return {providers,out,add};}
function listChats(userId, config={}){const a=chatAdder(userId);
  const sources=[['chat_registry',()=>arr(store.getChatsList&&store.getChatsList())],['config_chat_registry',()=>arr(config.chats||config.chatRegistry)]];
  for(const [name,fn] of sources){let list=[]; try{list=fn();}catch{} if(list.length)a.providers.push(name); list.forEach(x=>a.add(x,name,true));}
  return {chats:a.out, providers:a.providers, chatProviderAvailable:a.providers.length>0};}
async function connectedChatsForUser(userId, config={}){try{const r=await pushConnectedChatsService.resolveConnectedChats(clean(userId),{botToken:clean(config.botToken||process.env.BOT_TOKEN||process.env.MAX_BOT_TOKEN),endpointHash:clean(config.endpointHash),deviceId:clean(config.deviceId)});return arr(r&&r.chats);}catch{return []}}
async function listChatsAsync(userId, config={}){const base=listChats(userId,config);const a=chatAdder(userId);base.chats.forEach(c=>a.add(c,c.provider,false));a.providers.push(...base.providers);const connected=await connectedChatsForUser(userId,config);if(connected.length)a.providers.push('push_connected_chats');connected.forEach(c=>a.add(c,'push_connected_chats',true));return {chats:a.out,providers:[...new Set(a.providers)],chatProviderAvailable:a.providers.length>0};}
function normalizeOverrideTargets(list,kind){return arr(list).map(x=>({targetKind:clean(x.targetKind)||kind,targetId:clean(x.targetId||x.channelId||x.chatId),channelId:clean(x.channelId),chatId:clean(x.chatId),title:visibleName(x,kind==='chat'?'Чат без названия':'Канал без названия'),provider:'override'}));}
function buildResult(userId,channels,chat){const channelProviders=[...new Set(channels.map(c=>c.provider).filter(Boolean))]; const providersUsed=channelProviders.concat(chat.providers); return {ok:true,userId:clean(userId),channels,chats:chat.chats,targets:[...channels,...chat.chats],diagnostics:{providersUsed,channelProviderAvailable:channels.length>0,chatProviderAvailable:chat.chatProviderAvailable,chatProviders:chat.providers,pushSubscriptionsUsedAsStatsChats:false}};}
function listStatsTargetsForUser(userId, config={}){if(config.statsTargetsOverride){const channels=normalizeOverrideTargets(config.statsTargetsOverride.channels,'channel');const chats=normalizeOverrideTargets(config.statsTargetsOverride.chats,'chat');return {ok:true,userId:clean(userId),channels,chats,targets:[...channels,...chats],diagnostics:{providersUsed:['override'],channelProviderAvailable:true,chatProviderAvailable:chats.length>0,chatProviders:['override']}};} return buildResult(userId,listChannels(userId),listChats(userId,config));}
async function listStatsTargetsForUserAsync(userId, config={}){if(config.statsTargetsOverride)return listStatsTargetsForUser(userId,config); return buildResult(userId,listChannels(userId),await listChatsAsync(userId,config));}
module.exports={listStatsTargetsForUser,listStatsTargetsForUserAsync,_private:{boundToUser,channelPostBoundToUser,accessChannelsForUser,connectedChatsForUser}};
