'use strict';
const store = require('../store');
const tenantScope = require('../tenant-scope');
function clean(v){return String(v||'').replace(/\s+/g,' ').trim();}
function arr(v){return Array.isArray(v)?v:[];}
function visibleName(x, fallback){const s=clean(x.title||x.channelTitle||x.chatTitle||x.name||x.displayName);return s && !/^-?\d{5,}$/.test(s) ? s : fallback;}
function ownerFields(x={}){return [x.ownerUserId,x.linkedByUserId,x.userId,x.createdByUserId,x.adminId,x.updatedByUserId].map(clean).filter(Boolean);}
function tenantForUser(userId){try{return clean(tenantScope.ensureTenantContext(clean(userId)).tenantKey);}catch{return '';}}
function channelPostBoundToUser(channelId,userId){return arr(store.getPostsList&&store.getPostsList()).some(p=>clean(p.channelId)===clean(channelId)&&ownerFields(p).includes(clean(userId)));}
function boundToUser(x,userId,channelId=''){const uid=clean(userId); if(!uid)return false; if(ownerFields(x).includes(uid))return true; const tenant=tenantForUser(uid); if(tenant&&clean(x.tenantKey)===tenant)return true; if(channelId&&channelPostBoundToUser(channelId,uid))return true; return false;}
function listChannels(userId){const seen=new Set();return arr(store.getChannelsList&&store.getChannelsList()).filter(c=>{const id=clean(c.channelId||c.id); if(!id||seen.has(id))return false; if(!boundToUser(c,userId,id))return false; seen.add(id); return true;}).map(c=>({targetKind:'channel',targetId:clean(c.channelId||c.id),channelId:clean(c.channelId||c.id),chatId:'',title:visibleName(c,'Канал без названия'),provider:'channel_registry'}));}
function listChats(userId, config={}){const providers=[]; const out=[]; const seen=new Set(); const add=(c,provider)=>{const id=clean(c.chatId||c.id||c.requiredChatId); if(!id||seen.has(id))return; if(!boundToUser(c,userId,''))return; seen.add(id); out.push({targetKind:'chat',targetId:id,channelId:'',chatId:id,title:visibleName(c,'Чат без названия'),provider});};
  const sources=[['chat_registry',()=>arr(store.getChatsList&&store.getChatsList())],['config_chat_registry',()=>arr(config.chats||config.chatRegistry)]];
  for(const [name,fn] of sources){let list=[]; try{list=fn();}catch{} if(list.length)providers.push(name); list.forEach(x=>add(x,name));}
  return {chats:out, providers, chatProviderAvailable:providers.length>0};}
function normalizeOverrideTargets(list,kind){return arr(list).map(x=>({targetKind:clean(x.targetKind)||kind,targetId:clean(x.targetId||x.channelId||x.chatId),channelId:clean(x.channelId),chatId:clean(x.chatId),title:visibleName(x,kind==='chat'?'Чат без названия':'Канал без названия'),provider:'override'}));}
function listStatsTargetsForUser(userId, config={}){if(config.statsTargetsOverride){const channels=normalizeOverrideTargets(config.statsTargetsOverride.channels,'channel');const chats=normalizeOverrideTargets(config.statsTargetsOverride.chats,'chat');return {ok:true,userId:clean(userId),channels,chats,targets:[...channels,...chats],diagnostics:{providersUsed:['override'],channelProviderAvailable:true,chatProviderAvailable:chats.length>0,chatProviders:['override']}};} const channels=listChannels(userId); const chat=listChats(userId,config); const providersUsed=['channel_registry'].filter(()=>channels.length).concat(chat.providers); return {ok:true,userId:clean(userId),channels,chats:chat.chats,targets:[...channels,...chat.chats],diagnostics:{providersUsed,channelProviderAvailable:channels.length>0,chatProviderAvailable:chat.chatProviderAvailable,chatProviders:chat.providers,pushSubscriptionsUsedAsStatsChats:false}};}
module.exports={listStatsTargetsForUser,_private:{boundToUser,channelPostBoundToUser}};
