'use strict';
const store = require('../store');
const stats = require('./statsProductPerfectPr226');
function clean(v){return String(v||'').trim();}
function tenantFromChannel(channelId=''){const ch=store.getChannelsList().find(x=>clean(x.channelId)===clean(channelId))||{}; const owner=clean(ch.ownerUserId||ch.linkedByUserId||ch.userId||ch.createdByUserId); return {channel:ch,ownerUserId:owner,tenantKey:clean(ch.tenantKey||ch.tenantId||owner)};}
function resolveStatsProducerContext(input={}){const explicitTenant=clean(input.tenantKey), explicitOwner=clean(input.ownerUserId||input.adminId); let commentKey=clean(input.commentKey), channelId=clean(input.channelId||input.chatId), postId=clean(input.postId), messageId=clean(input.messageId); let ownerUserId=explicitOwner, tenantKey=explicitTenant; const post=commentKey?store.getPost(commentKey):null; if(post){channelId=channelId||clean(post.channelId); postId=postId||clean(post.postId||post.messageId); messageId=messageId||clean(post.messageId); commentKey=commentKey||clean(post.commentKey); ownerUserId=ownerUserId||clean(post.ownerUserId||post.createdByUserId||post.userId); tenantKey=tenantKey||clean(post.tenantKey||post.tenantId||ownerUserId);} if(channelId&&(!ownerUserId||!tenantKey)){const r=tenantFromChannel(channelId); ownerUserId=ownerUserId||r.ownerUserId; tenantKey=tenantKey||r.tenantKey;} ownerUserId=ownerUserId||clean(input.campaignOwnerUserId||input.createdByUserId); tenantKey=tenantKey||clean(input.campaignTenantKey||ownerUserId); const unavailable=!(tenantKey||ownerUserId); return {tenantKey:tenantKey||'',ownerUserId:ownerUserId||'',channelId,postId,messageId,commentKey,confidence:unavailable?'unavailable':'exact',unavailable};}
function withConfidence(c,input={}){return {...c,confidence:c.confidence||'exact',payload:input};}
function recordAudienceUpdate(input={}){const c=resolveStatsProducerContext(input); const kind=clean(input.type||input.updateType||input.eventType).toLowerCase(); if(kind.includes('added')) return stats.recordMemberJoined(c,{userId:clean(input.memberUserId||input.userId),timestamp:input.timestamp,confidence:c.confidence,source:clean(input.source),campaign:clean(input.campaign),medium:clean(input.medium),content:clean(input.content),term:clean(input.term),linkId:clean(input.linkId||input.slug),payload:input}); if(kind.includes('removed')) return stats.persistStatsEvent({...withConfidence(c,input),userId:clean(input.memberUserId||input.userId),eventType:'member_left',timestamp:input.timestamp}); return null;}
const ADMIN_CTA_DENYLIST = new Set(['admin_section_buttons','button_admin_channel_pick','button_admin_recent_posts','button_admin_post_pick','button_admin_selected_post','button_admin_add','button_admin_edit','button_admin_delete','button_admin_save','button_admin_cancel','button_admin_back','button_admin_root','button_admin_set_text','button_admin_set_url']);
function isUserFacingCtaClick(payload={},context={}){const a=clean(payload.action||context.action).toLowerCase(); const kind=clean(payload.kind||context.kind).toLowerCase(); const source=clean(payload.buttonSource||payload.sourceType||context.buttonSource||context.sourceType).toLowerCase(); if(!a&&!kind&&!source) return false; if(ADMIN_CTA_DENYLIST.has(a)) return false; if(a.startsWith('admin_')||a.startsWith('button_admin_')) return false; if(/(^|_)(setup|config|configure|edit|delete|save|cancel|back|root|select|selected|channel_pick|recent_posts|post_pick|set_text|set_url)(_|$)/.test(a)) return false; if(kind==='public_cta'||kind==='published_post_cta') return true; if(source==='published_post'||source==='public_cta'||source==='tracking_redirect') return true; return a==='public_cta'||a==='published_post_cta'||a==='tracking_cta_clicked';}
function recordCtaClick(input={}){if(!isUserFacingCtaClick(input,input)) return null; const c=resolveStatsProducerContext(input); return stats.persistStatsEvent({...withConfidence(c,input),eventType:'cta_clicked',userId:clean(input.userId),linkId:clean(input.buttonId||input.linkId),content:clean(input.buttonText),source:clean(input.source),campaign:clean(input.campaign)});}
function recordGiftRequested(input={}){const c=resolveStatsProducerContext(input); return stats.persistStatsEvent({...withConfidence(c,input),eventType:'gift_requested',userId:clean(input.userId),content:clean(input.campaignId||input.giftId)});}
function recordGiftClaimed(input={}){const c=resolveStatsProducerContext(input); return stats.persistStatsEvent({...withConfidence(c,input),eventType:'gift_claimed',userId:clean(input.userId),content:clean(input.campaignId||input.giftId)});}
function recordCommentCreated(input={}){const c=resolveStatsProducerContext(input); return stats.persistStatsEvent({...withConfidence(c,input),eventType:'comment_created',userId:clean(input.userId)});}
module.exports={resolveStatsProducerContext,isUserFacingCtaClick,recordAudienceUpdate,recordCtaClick,recordGiftRequested,recordGiftClaimed,recordCommentCreated};
