'use strict';
const store = require('../store');
function clean(v){return String(v||'').replace(/\s+/g,' ').trim();}
function arr(v){return Array.isArray(v)?v:[];}
function visibleName(x, fallback){const s=clean(x.title||x.channelTitle||x.chatTitle||x.name||x.displayName);return s && !/^-?\d{5,}$/.test(s) ? s : fallback;}
function listChannels(userId){const seen=new Set();return arr(store.getChannelsList&&store.getChannelsList()).filter(c=>{const id=clean(c.channelId||c.id); if(!id||seen.has(id))return false; const owner=clean(c.ownerUserId||c.linkedByUserId||c.userId||c.createdByUserId); if(owner&&clean(userId)&&owner!==clean(userId))return false; seen.add(id); return true;}).map(c=>({targetKind:'channel',targetId:clean(c.channelId||c.id),channelId:clean(c.channelId||c.id),chatId:'',title:visibleName(c,'Канал без названия'),provider:'channel_registry'}));}
function listChats(userId, config={}){const providers=[]; const out=[]; const seen=new Set(); const add=(c,provider)=>{const id=clean(c.chatId||c.id||c.requiredChatId); if(!id||seen.has(id))return; const owner=clean(c.ownerUserId||c.userId||c.createdByUserId||c.adminId); if(owner&&clean(userId)&&owner!==clean(userId))return; seen.add(id); out.push({targetKind:'chat',targetId:id,channelId:'',chatId:id,title:visibleName(c,'Чат без названия'),provider});};
  const sources=[['push_subscription_registry',()=>arr(store.getPushSubscriptions&&store.getPushSubscriptions())],['chat_registry',()=>arr(store.getChatsList&&store.getChatsList())],['config_chat_registry',()=>arr(config.chats||config.chatRegistry)]];
  for(const [name,fn] of sources){let list=[]; try{list=fn();}catch{} if(list.length)providers.push(name); list.forEach(x=>add(x,name));}
  return {chats:out, providers, chatProviderAvailable:providers.length>0};}
function listStatsTargetsForUser(userId, config={}){if(config.statsTargetsOverride)return {ok:true,userId:clean(userId),channels:arr(config.statsTargetsOverride.channels),chats:arr(config.statsTargetsOverride.chats),targets:[...arr(config.statsTargetsOverride.channels),...arr(config.statsTargetsOverride.chats)],diagnostics:{providersUsed:['override'],channelProviderAvailable:true,chatProviderAvailable:arr(config.statsTargetsOverride.chats).length>0,chatProviders:['override']}}; const channels=listChannels(userId); const chat=listChats(userId,config); const providersUsed=['channel_registry'].filter(()=>channels.length).concat(chat.providers); return {ok:true,userId:clean(userId),channels,chats:chat.chats,targets:[...channels,...chat.chats],diagnostics:{providersUsed,channelProviderAvailable:true,chatProviderAvailable:chat.chatProviderAvailable,chatProviders:chat.providers}};}
module.exports={listStatsTargetsForUser};
