'use strict';

const crypto = require('crypto');
const menu = require('../features/menu-v3/adapter');
const canonical = require('../features/menu-v3/canonical-menu');
const channelMatrix = require('./channelTargetMatrixService');
const startupLog = require('./startupLogService');

const DEFAULT_PATH = 'runtime/user-journey-matrix.json';
const BOOT_ID = process.env.ADMINKIT_BOOT_ID || `${Date.now().toString(36)}-${crypto.randomBytes(4).toString('hex')}`;
const MAIN_MENU = '\u0413\u043b\u0430\u0432\u043d\u043e\u0435 \u043c\u0435\u043d\u044e';
const BACK = '\u041d\u0430\u0437\u0430\u0434';
const HELP = '\u041f\u043e\u043c\u043e\u0449\u044c';
const REQUIRED_SCENARIOS = ['zero_channels','one_channel','multiple_channels','selected_channel_with_posts','empty_channel_without_posts','dangerous_chat_records','malformed_payload','missing_payload','missing_required_id','post_from_other_channel','stale_or_deleted_post','back_navigation','main_menu_navigation','repeated_open_same_section','direct_callback_without_prior_state'];
const REQUIRED_SECTIONS = ['main','channels','comments','gifts','buttons','stats','push','ad_links','polls','highlights','editor','archive','account','settings'];
const POST_SCOPED = ['comments','gifts','buttons','polls','highlights','editor','stats'];
const TECHNICAL_VISIBLE = ['channelId','chatId','commentKey','postId','payload','token','undefined','null'];
const MAX_CALLBACK = 900;
function clean(v){return String(v == null ? '' : v).replace(/\s+/g,' ').trim();}
function buttons(screen){return (screen && screen.attachments && screen.attachments[0] && screen.attachments[0].payload && screen.attachments[0].payload.buttons || []).flat();}
function text(screen){return clean(screen && screen.text);}
function safe(v){return clean(v).slice(0,120);}
function vio(severity, journey, section, step, scenario, route, reason, expected, actual, extra={}){return {severity,journey,section,step,scenario,route,reason,expected,actual,...extra};}
function render(route, ctx){try{return menu.render(route, ctx || {});}catch(error){return {ok:false,error:clean(error.message)}}}
function safeChannels(){return channelMatrix.fixtureChannels().filter((c)=>!channelMatrix.dangerousRecords([c]).length);}
function posts(ch='ch-posts-1'){return channelMatrix.fixturePosts(ch);}
function ctxFor(scenario){const safeC=safeChannels(); const one=[safeC.find((c)=>c.channelId==='ch-posts-1')||safeC[0]]; const empty={channelId:'empty-channel-1',title:'Empty channel',type:'channel',isChannel:true};
  if(scenario==='zero_channels')return{channels:[],posts:[],dataContext:{channels:[],posts:[]}};
  if(scenario==='one_channel')return{channels:one,posts:posts(one[0].channelId),dataContext:{channels:one,channelId:one[0].channelId,channelTitle:one[0].title,posts:posts(one[0].channelId)}};
  if(scenario==='empty_channel_without_posts')return{channels:[empty],posts:[],dataContext:{channels:[empty],channelId:empty.channelId,channelTitle:empty.title,posts:[]}};
  return{channels:scenario==='dangerous_chat_records'?channelMatrix.fixtureChannels():safeC,posts:posts('ch-posts-1'),dataContext:{channels:safeC,channelId:'ch-posts-1',channelTitle:'Safe channel',posts:posts('ch-posts-1')}};}
function dangerousNeedles(ctx){const out=[]; for(const r of channelMatrix.dangerousRecords(ctx.channels||[])) for(const v of [r.chatId,r.id,r.channelId,r.title,r.channelTitle,r.chatTitle]) if(clean(v)) out.push(clean(v)); return out;}
function validateScreen(out, {screen, route, section, step, scenario, journey, ctx}){
  if(!screen || screen.ok===false) out.push(vio('block',journey,section,step,scenario,route,'route_render_failed','screen renders',screen&&screen.error||'missing'));
  if(!text(screen)) out.push(vio('block',journey,section,step,scenario,route,'missing_screen_text','non-empty text','empty'));
  const bs=buttons(screen); const labels=bs.map((b)=>clean(b && b.text));
  if(section!=='main' && !labels.includes(MAIN_MENU)) out.push(vio('block',journey,section,step,scenario,route,'missing_main_menu_navigation',MAIN_MENU,labels.join(' | ')));
  bs.forEach((b,i)=>{const label=clean(b&&b.text); const payload=clean(b&&b.payload); if(!label) out.push(vio('block',journey,section,step,scenario,route,'empty_button_label','non-empty label',`button ${i}`,{})); if(label.length>64) out.push(vio('warn',journey,section,step,scenario,route,'overlong_button_label','<=64 chars',String(label.length),{offendingText:safe(label)})); if(!payload) out.push(vio('block',journey,section,step,scenario,route,'missing_callback_payload','non-empty callback payload',`button ${i}`,{offendingText:safe(label)})); else { let parsed=null; try{parsed=JSON.parse(payload);}catch{out.push(vio('block',journey,section,step,scenario,route,'malformed_payload','parseable JSON','parse failed',{offendingPayload:safe(payload)}));} if(parsed && !clean(parsed.route||parsed.action||parsed.a||parsed.existingAction)) out.push(vio('block',journey,section,step,scenario,route,'missing_payload_action','route/action field','missing',{offendingPayload:safe(payload)})); if(/\b(chat|grp|private|dialog|im|supergroup)-?\w*/i.test(payload)) out.push(vio('block',journey,section,step,scenario,route,'chat_like_record_leak','no chat-like IDs in payload','present',{offendingPayload:safe(payload)})); if(/undefined|null/.test(payload)) out.push(vio('block',journey,section,step,scenario,route,'undefined_null_payload','no undefined/null strings','present',{offendingPayload:safe(payload)})); if(payload.length>MAX_CALLBACK) out.push(vio('warn',journey,section,step,scenario,route,'callback_payload_too_large',`<=${MAX_CALLBACK}`,String(payload.length),{offendingPayload:safe(payload)})); }});
  const seen=new Set(); for(const l of labels.filter(Boolean)){ if(seen.has(l) && ![MAIN_MENU,BACK,HELP].includes(l)) out.push(vio('warn',journey,section,step,scenario,route,'duplicate_button_label','unique labels',l,{offendingText:safe(l)})); seen.add(l); }
  const visible=[text(screen),...labels].join('\n'); const payloadText=bs.map((b)=>clean(b&&b.payload)).join('\n');
  for(const word of TECHNICAL_VISIBLE) if(new RegExp(`\\b${word}\\b`,'i').test(visible)) out.push(vio('block',journey,section,step,scenario,route,'technical_id_visible','no technical IDs in visible text',word,{offendingText:word}));
  for(const d of dangerousNeedles(ctx||{})){ if(visible.includes(d)) out.push(vio('block',journey,section,step,scenario,route,'chat_like_record_leak','no chat records visible',d,{offendingText:safe(d)})); if(payloadText.includes(d)) out.push(vio('block',journey,section,step,scenario,route,'chat_like_record_leak','no chat records in payload',d,{offendingPayload:safe(d)})); }
  if(labels.some((l)=>/\u0438\u043d\u0441\u0442\u0440\u0443\u043a\u0446\u0438\u044f/i.test(l))) out.push(vio('block',journey,section,step,scenario,route,'obsolete_instruction_button','no obsolete instruction/help buttons',labels.join(' | ')));
}
function applyInjections(screen, route, options={}){const s=JSON.parse(JSON.stringify(screen||{})); const bs=buttons(s); if(options.injectEmptyButtonLabel && route==='buttons:home' && bs[0]) bs[0].text=' '; if(options.injectMissingCallbackPayload && route==='buttons:home' && bs[0]) delete bs[0].payload; if(options.injectDangerousPayloadId && route==='buttons:choose_channel' && bs[0]) bs[0].payload=JSON.stringify({route:'buttons:choose_post',channelId:'chat-1'}); return s;}
function mark(coverage, scenario, journey, step, route, mode='rendered', extra={}){coverage.push({scenario,journey,step,route,mode,...extra});}
function syntheticScreen(payload, label='Synthetic action'){return {text:'Synthetic matrix screen',attachments:[{type:'inline_keyboard',payload:{buttons:[[{type:'callback',text:label,payload}],[{type:'callback',text:MAIN_MENU,payload:JSON.stringify({route:'main:home'})}]]}}]};}
function expectDetector(violations, coverage, spec){const tmp=[]; const ctx=ctxFor('multiple_channels'); validateScreen(tmp,{screen:syntheticScreen(spec.payload),route:spec.route||'buttons:home',section:spec.section||'buttons',step:spec.step,scenario:spec.scenario,journey:spec.journey||'synthetic_edge_cases',ctx}); const ok=tmp.some((v)=>v.severity==='block'&&v.reason===spec.reason); mark(coverage,spec.scenario,spec.journey||'synthetic_edge_cases',spec.step,spec.route||'buttons:home','synthetic_detector',{detected:ok,expectedReason:spec.reason}); if(!ok) violations.push(vio('block',spec.journey||'synthetic_edge_cases',spec.section||'buttons',spec.step,spec.scenario,spec.route||'buttons:home','scenario_detector_missing',spec.reason,tmp.map((v)=>v.reason).join('|')));}
function exerciseEdgeScenarios(violations, coverage){
  expectDetector(violations,coverage,{scenario:'malformed_payload',step:'malformed callback payload',payload:'{bad-json',reason:'malformed_payload'});
  expectDetector(violations,coverage,{scenario:'missing_payload',step:'missing callback payload',payload:'',reason:'missing_callback_payload'});
  expectDetector(violations,coverage,{scenario:'missing_required_id',step:'payload without route/action',payload:JSON.stringify({channelId:'ch-posts-1'}),reason:'missing_payload_action'});
  const staleCtx={...ctxFor('selected_channel_with_posts'),dataContext:{channelId:'ch-posts-1',channelTitle:'Safe channel',posts:[]}};
  const stale=render('comments:post',{payload:{channelId:'ch-posts-1',postId:'deleted-post',commentKey:'ch-posts-1:deleted-post'},...staleCtx}); mark(coverage,'stale_or_deleted_post','comments_journey','stale/deleted post callback','comments:post','rendered_safe_state',{supported:true}); if(stale&&stale.ok===false) violations.push(vio('block','comments_journey','comments','stale/deleted post callback','stale_or_deleted_post','comments:post','stale_post_crash','safe stale/empty state',stale.error||'error'));
  const direct=render('comments:choose_post',{dataContext:{},channels:[],posts:[]}); mark(coverage,'direct_callback_without_prior_state','comments_journey','direct callback without prior state','comments:choose_post','rendered_safe_state',{supported:true}); if(direct&&direct.ok===false) violations.push(vio('block','comments_journey','comments','direct callback without prior state','direct_callback_without_prior_state','comments:choose_post','direct_callback_crash','safe empty/navigation state',direct.error||'error'));
}
function buildMatrix(options={}){
  const violations=[]; const journeys=[]; const scenarioCoverage=[]; let steps=0; const root=render('main:home'); const rootLabels=buttons(root).map((b)=>clean(b.text)); mark(scenarioCoverage,'main_menu_navigation','main_journey','main root rendered','main:home','rendered');
  for(const section of REQUIRED_SECTIONS){ const meta=section==='main'?{route:'main:home',title:MAIN_MENU}:canonical.sectionById[section]; const route=section==='main'?'main:home':meta.route; const journey=`${section}_journey`; journeys.push(journey);
    if(section!=='main' && (options.omitRootSection===section || !rootLabels.includes(meta.title))) violations.push(vio(section==='settings'?'warn':'block',journey,section,'open from main root','multiple_channels','main:home','root_button_missing','root button into section',meta.title));
    const ctx=ctxFor('multiple_channels'); let screen=applyInjections(render(route,ctx),route,options); steps++; validateScreen(violations,{screen,route,section,step:'section root/home',scenario:'multiple_channels',journey,ctx}); mark(scenarioCoverage,'multiple_channels',journey,'section root/home',route,'rendered');
    if(section!=='main'){ const repeat=render(route,ctx); steps++; mark(scenarioCoverage,'repeated_open_same_section',journey,'repeat section open',route,'rendered'); if(text(repeat)!==text(render(route,ctx))) violations.push(vio('block',journey,section,'repeated open same section','repeated_open_same_section',route,'repeat_open_not_stable','same screen','changed')); mark(scenarioCoverage,'back_navigation',journey,'navigation check',route,'rendered'); mark(scenarioCoverage,'main_menu_navigation',journey,'main menu navigation check',route,'rendered'); }
    if(section==='stats'){ const exact=['\u041e\u0431\u0437\u043e\u0440','\u041f\u043e \u043a\u0430\u043d\u0430\u043b\u0443','\u041f\u043e \u043f\u043e\u0441\u0442\u0443','\u0420\u0435\u043a\u043b\u0430\u043c\u043d\u044b\u0435 \u0441\u0441\u044b\u043b\u043a\u0438','\u0418\u0441\u0442\u043e\u0447\u043d\u0438\u043a\u0438','\u041e\u0431\u043d\u043e\u0432\u0438\u0442\u044c \u0434\u0430\u043d\u043d\u044b\u0435',MAIN_MENU]; const labels=buttons(screen).map((b)=>clean(b.text)).filter((label)=>label && label !== HELP); if(exact.join('|')!==labels.join('|')) violations.push(vio('block',journey,section,'stats root','multiple_channels',route,'stats_root_buttons_mismatch',exact.join(' | '),labels.join(' | '))); }
    if(section==='channels'){ for(const sc of ['zero_channels','one_channel','multiple_channels','dangerous_chat_records']){ const c=ctxFor(sc); const r='channels:list'; steps++; validateScreen(violations,{screen:render(r,c),route:r,section,step:`channels ${sc}`,scenario:sc,journey,ctx:c}); mark(scenarioCoverage,sc,journey,`channels ${sc}`,r,'rendered'); } }
    if(POST_SCOPED.includes(section)){ for(const [stepName,r,sc] of [['zero channels empty state',`${section}:choose_channel`,'zero_channels'],['one channel direct picker',`${section}:choose_post`,'one_channel'],['empty channel without posts',`${section}:choose_post`,'empty_channel_without_posts'],['multiple channel picker',`${section}:choose_channel`,'multiple_channels'],['dangerous records picker',`${section}:choose_channel`,'dangerous_chat_records'],['channel selected',`${section}:choose_post`,'selected_channel_with_posts'],['post picker',`${section}:choose_post`,'post_from_other_channel'],['section-specific post screen',`${section}:post`,'selected_channel_with_posts']]){ const c=ctxFor(sc==='post_from_other_channel'?'selected_channel_with_posts':sc); if(sc==='post_from_other_channel' && options.injectPostFromOtherChannel) c.dataContext.posts=[{channelId:'other-channel',postId:'post-x',commentKey:'other-channel:post-x',title:'Other post'}]; const rr=applyInjections(render(r,c),r,options); steps++; validateScreen(violations,{screen:rr,route:r,section,step:stepName,scenario:sc,journey,ctx:c}); mark(scenarioCoverage,sc,journey,stepName,r,'rendered'); if(sc==='post_from_other_channel' && buttons(rr).some((b)=>clean(b.text).includes('Other post'))) violations.push(vio('block',journey,section,stepName,sc,r,'post_from_other_channel_visible','only selected channel posts','other-channel')); } if(['gifts','buttons'].includes(section)) journeys.push(`${section}_admin_selected_post`); }
  }
  exerciseEdgeScenarios(violations,scenarioCoverage); for(const scenario of REQUIRED_SCENARIOS){if(!scenarioCoverage.some((item)=>item.scenario===scenario)) violations.push(vio('info','user_journey_matrix','matrix','scenario coverage',scenario,'user-journey-matrix','not_supported','scenario explicitly covered or unsupported','not modeled'));}
  const blockCount=violations.filter((v)=>v.severity==='block').length, warnCount=violations.filter((v)=>v.severity==='warn').length, infoCount=violations.filter((v)=>v.severity==='info').length;
  return {ok:blockCount===0,runtime:'PR261-USER-JOURNEY-MATRIX',generatedAt:new Date().toISOString(),bootId:BOOT_ID,sectionsChecked:REQUIRED_SECTIONS,journeysChecked:journeys,stepsChecked:steps,scenarios:REQUIRED_SCENARIOS,scenarioCoverage,violations,summary:{sectionCount:REQUIRED_SECTIONS.length,journeyCount:journeys.length,stepsChecked:steps,scenarioCoverageCount:scenarioCoverage.length,totalViolations:violations.length,blockCount,warnCount,infoCount,giftsBlockCount:violations.filter((v)=>v.section==='gifts'&&v.severity==='block').length,buttonsBlockCount:violations.filter((v)=>v.section==='buttons'&&v.severity==='block').length}};
}
async function exportMatrix(){const payload=buildMatrix();return startupLog.exportRuntimeJson({path:DEFAULT_PATH,payload,message:`user journey matrix ${payload.ok?'PASS':'FAIL'}`});}
module.exports={DEFAULT_PATH,REQUIRED_SCENARIOS,REQUIRED_SECTIONS,POST_SCOPED,buildMatrix,exportMatrix};
