'use strict';

const stateManager = require('./stateManager');
const definitions = require('./flowDefinitions');
const conditionCatalog = require('./leadMagnetConditionCatalog');

const RUNTIME = 'ADMINKIT-CORE-FLOW-ENGINE-1.40.3-EDIT-MATERIAL-SKIP-CONDITIONS';

function adminIdOf(ctx = {}) { return String(ctx.adminId || ctx.admin_id || 'debug-admin'); }
function cleanValue(value) { const raw = String(value ?? '').trim(); if (!raw) return ''; try { return decodeURIComponent(raw.replace(/\+/g, ' ')).trim(); } catch { return raw.replace(/\+/g, ' ').trim(); } }
function cut(value = '', max = 120) { const s = cleanValue(value); return s.length > max ? `${s.slice(0, Math.max(1, max - 1))}…` : s; }
function normalizeUrl(value) { const raw = cleanValue(value); if (!raw) return ''; if (/^https?:\/\//i.test(raw)) return raw; if (/^[a-z0-9.-]+\.[a-z]{2,}(\/.*)?$/i.test(raw)) return `https://${raw}`; return raw; }
function isValidHttpUrl(value) { const raw = normalizeUrl(value); try { const url = new URL(raw); return ['http:', 'https:'].includes(url.protocol) && !!url.hostname && url.hostname.includes('.'); } catch { return false; } }
function mergeDraft(oldDraft = {}, patch = {}) { return { ...(oldDraft || {}), ...(patch || {}) }; }
function sessionPatchFromDraft(draft = {}) { const patch = {}; if (draft.channelId || draft.selected_channel_id) patch.selected_channel_id = String(draft.channelId || draft.selected_channel_id || ''); if (draft.postId || draft.selected_post_id) patch.selected_post_id = String(draft.postId || draft.selected_post_id || ''); if (draft.commentKey || draft.selected_comment_key) patch.selected_comment_key = String(draft.commentKey || draft.selected_comment_key || ''); return patch; }
function valueFromCtx(ctx = {}, key, aliases = []) { for (const name of [key, ...aliases]) { const value = ctx[name] || ctx.payload?.[name] || ctx.update?.[name] || ctx.update?.query?.[name] || ctx.update?.body?.[name]; const cleaned = cleanValue(value); if (cleaned) return cleaned; } return ''; }
function textInputFromCtx(ctx = {}) { return cleanValue(ctx.text || ctx.messageText || ctx.inputText || ctx.payload?.text || ctx.update?.text || ctx.update?.query?.text || ctx.update?.body?.text || ctx.update?.message?.text || ''); }
function numberFromCtx(ctx = {}, key = 'value') { const n = Number(valueFromCtx(ctx, key, ['count', 'min', 'amount'])); return Number.isFinite(n) && n > 0 ? Math.floor(n) : 0; }
function conditionTitle(id = '') { return conditionCatalog.find(id)?.title || id || 'условие'; }
function postTitleOf(value = '', fallback = '') { return cleanValue(value) || cleanValue(fallback) || 'выбранный пост'; }
function channelTitleOf(value = '', fallback = '') { return cleanValue(value) || cleanValue(fallback) || 'выбранный канал'; }

async function getCurrent(ctx = {}) { const adminId = adminIdOf(ctx); const session = await stateManager.getSession(adminId); if (!session?.active_flow) return { ok: false, error: 'no_active_flow', session }; const flow = definitions.getFlow(session.active_flow); const step = definitions.getStep(session.active_flow, session.active_step) || definitions.firstStep(session.active_flow); return { ok: !!flow, flow, step, session, draft: session?.draft || {} }; }
async function start(ctx = {}, flowId, draft = {}) { const flow = definitions.getFlow(flowId); if (!flow) return { ok: false, error: 'unknown_flow', flowId }; const step = definitions.firstStep(flowId); const adminId = adminIdOf(ctx); const nextDraft = mergeDraft(draft, { runtimeVersion: RUNTIME, startedAt: new Date().toISOString() }); const session = await stateManager.upsertSession(adminId, { active_section: flow.section, active_flow: flow.id, active_step: step.id, selected_channel_id: ctx.channelId || ctx.payload?.channelId || draft.channelId || '', selected_post_id: ctx.postId || ctx.payload?.postId || draft.postId || '', selected_comment_key: ctx.commentKey || ctx.payload?.commentKey || draft.commentKey || '', draft: nextDraft }); return { ok: true, flow, step, session, draft: nextDraft }; }
async function patchDraft(ctx = {}, patch = {}) { const adminId = adminIdOf(ctx); const session = await stateManager.getSession(adminId); const nextDraft = mergeDraft(session?.draft || {}, patch); const next = await stateManager.upsertSession(adminId, { ...sessionPatchFromDraft(nextDraft), draft: nextDraft }); const flow = definitions.getFlow(next.active_flow); const step = definitions.getStep(next.active_flow, next.active_step); return { ok: true, flow, step, session: next, draft: nextDraft }; }
async function goTo(ctx = {}, stepId, patch = {}) { const current = await getCurrent(ctx); if (!current.ok) return current; const step = definitions.getStep(current.flow.id, stepId); if (!step) return { ok: false, error: 'unknown_step', flowId: current.flow.id, stepId }; const adminId = adminIdOf(ctx); const nextDraft = mergeDraft(current.draft, patch); const session = await stateManager.upsertSession(adminId, { active_step: step.id, ...sessionPatchFromDraft(nextDraft), draft: nextDraft }); return { ok: true, flow: current.flow, step, session, draft: nextDraft }; }
async function next(ctx = {}, patch = {}) { const current = await getCurrent(ctx); if (!current.ok) return current; const step = definitions.nextStep(current.flow.id, current.step?.id); if (!step) return { ok: false, error: 'flow_finished', flow: current.flow, session: current.session, draft: current.draft }; const adminId = adminIdOf(ctx); const nextDraft = mergeDraft(current.draft, patch); const session = await stateManager.upsertSession(adminId, { active_step: step.id, ...sessionPatchFromDraft(nextDraft), draft: nextDraft }); return { ok: true, flow: current.flow, step, session, draft: nextDraft }; }

async function selectChannel(ctx = {}) { const current = await getCurrent(ctx); if (!current.ok) return current; if (current.step?.id !== 'select_channel') return { ok: false, error: 'unexpected_step', expected: 'select_channel', actual: current.step?.id || '', flow: current.flow, step: current.step, draft: current.draft }; const channelId = valueFromCtx(ctx, 'channelId', ['selectedChannelId']); if (!channelId) return { ok: false, error: 'channel_required', flow: current.flow, step: current.step, draft: current.draft }; const channelTitle = valueFromCtx(ctx, 'channelTitle', ['channelName']) || 'Канал'; return next(ctx, { channelId, channelTitle, channelSelectedAt: new Date().toISOString() }); }
async function selectPostSource(ctx = {}) { const current = await getCurrent(ctx); if (!current.ok) return current; if (current.step?.id !== 'select_post_source') return { ok: false, error: 'unexpected_step', expected: 'select_post_source', actual: current.step?.id || '', flow: current.flow, step: current.step, draft: current.draft }; const postSource = valueFromCtx(ctx, 'postSource', ['source']) || 'registry'; const postSourceLabel = valueFromCtx(ctx, 'postSourceLabel', ['label']) || (postSource === 'forwarded_post' ? 'переслать пост из канала' : postSource === 'old_post' ? 'найти/переслать старый пост' : 'выбрать из базы'); return next(ctx, { postSource, postSourceLabel, postSourceSelectedAt: new Date().toISOString() }); }
async function selectPost(ctx = {}, explicitPostId = '', patch = {}) { const current = await getCurrent(ctx); if (!current.ok) return current; const requestedFlowId = valueFromCtx(ctx, 'flowId', ['activeFlow', 'active_flow']); if (requestedFlowId && requestedFlowId !== current.flow?.id) return { ok: false, error: 'stale_flow_callback', expectedFlow: current.flow?.id || '', actualFlow: requestedFlowId, flow: current.flow, step: current.step, draft: current.draft }; if (current.step?.id !== 'select_post') return { ok: false, error: 'unexpected_step', expected: 'select_post', actual: current.step?.id || '', flow: current.flow, step: current.step, draft: current.draft }; const postId = String(explicitPostId || valueFromCtx(ctx, 'postId', ['selectedPostId', 'id']) || '').trim(); if (!postId) return { ok: false, error: 'post_required', flow: current.flow, step: current.step, draft: current.draft }; const channelId = valueFromCtx(ctx, 'channelId', ['selectedChannelId']) || current.draft.channelId; const commentKey = valueFromCtx(ctx, 'commentKey', ['selectedCommentKey']); const postTitle = valueFromCtx(ctx, 'postTitle', ['title', 'postPreview', 'displayTitle']); const channelTitle = valueFromCtx(ctx, 'channelTitle', ['channelName', 'channelDisplayName']) || current.draft.channelTitle; return next(ctx, { ...patch, postId, ...(channelId ? { channelId } : {}), ...(channelTitle ? { channelTitle } : {}), ...(commentKey ? { commentKey } : {}), ...(postTitle ? { postTitle } : {}), postSelectedAt: new Date().toISOString(), postSource: patch.postSource || current.draft.postSource || 'registry_or_debug' }); }
async function capturePost(ctx = {}) { const current = await getCurrent(ctx); if (!current.ok) return current; if (!['select_post', 'select_post_source'].includes(current.step?.id)) return { ok: false, error: 'unexpected_step', expected: 'select_post_or_select_post_source', actual: current.step?.id || '', flow: current.flow, step: current.step, draft: current.draft }; const mode = valueFromCtx(ctx, 'captureMode', ['mode']) || valueFromCtx(ctx, 'postSource') || 'forwarded_post'; const label = mode === 'legacy_or_old_post' || mode === 'old_post' ? 'найти старый пост / переслать старый пост' : 'переслать пост из канала'; return goTo(ctx, 'select_post', { captureMode: mode, captureModeLabel: label, postSource: mode, postCaptureRequestedAt: new Date().toISOString(), postCaptureInstruction: 'Администратор должен переслать пост из канала; clean adapter распознает payload и запишет post registry.' }); }

async function selectConditionGroup(ctx = {}) { const current = await getCurrent(ctx); if (!current.ok) return current; if (current.step?.id !== 'select_condition_group') return { ok: false, error: 'unexpected_step', expected: 'select_condition_group', actual: current.step?.id || '', flow: current.flow, step: current.step, draft: current.draft }; const group = valueFromCtx(ctx, 'conditionGroup', ['group']) || 'all'; const label = valueFromCtx(ctx, 'conditionGroupLabel', ['label']) || group; return next(ctx, { conditionGroup: group, conditionGroupLabel: label }); }
async function selectAccess(ctx = {}) { const current = await getCurrent(ctx); if (!current.ok) return current; const requestedFlowId = valueFromCtx(ctx, 'flowId', ['activeFlow', 'active_flow']); if (requestedFlowId && requestedFlowId !== current.flow?.id) return { ok: false, error: 'stale_flow_callback', expectedFlow: current.flow?.id || '', actualFlow: requestedFlowId, flow: current.flow, step: current.step, draft: current.draft }; if (current.flow?.id !== 'lead_magnets.create' || current.step?.id !== 'select_access') return { ok: false, error: 'unexpected_step', expected: 'lead_magnets.create/select_access', actual: `${current.flow?.id || ''}/${current.step?.id || ''}`, flow: current.flow, step: current.step, draft: current.draft }; const conditionId = valueFromCtx(ctx, 'conditionId', ['condition']); const accessMode = valueFromCtx(ctx, 'accessMode', ['mode']) || 'subscribers_current_channel'; const verifier = valueFromCtx(ctx, 'verifier', ['conditionVerifier']); const catalogCondition = conditionCatalog.toCondition({ conditionId, accessMode, mode: accessMode, params: {} }); const accessLabel = valueFromCtx(ctx, 'accessLabel', ['label']) || catalogCondition.title || accessMode; const isCombined = ['all_conditions', 'any_condition'].includes(catalogCondition.id); const conditions = isCombined ? { ...catalogCondition, operator: catalogCondition.id === 'any_condition' ? 'any' : 'all', items: [] } : catalogCondition; return next(ctx, { accessMode: catalogCondition.mode, accessLabel, conditionId: catalogCondition.id, conditionVerifier: verifier || catalogCondition.verifier, conditions, conditionSetupStatus: 'needs_setup', accessSelectedAt: new Date().toISOString() }); }

function conditionNeedsSetup(condition = {}) { const id = condition.id || condition.mode || ''; return ['subscribe_one_channel','subscribe_many_channels','comment_on_post','comment_count_on_post','comment_keyword','reaction_on_post','reaction_count_on_post','quiz_answer','quiz_correct_answer','all_conditions','any_condition'].includes(id); }
function completeCondition(draft = {}, patch = {}) { const base = draft.conditions || {}; const condition = { ...base, params: { ...(base.params || {}), ...(patch.params || {}) }, setupComplete: true }; return { conditions: condition, conditionSetupStatus: 'complete', ...patch.extra }; }
function simpleCondition(id, params = {}, summary = '') { return { id, mode: conditionCatalog.find(id)?.accessMode || id, title: conditionTitle(id), verifier: conditionCatalog.find(id)?.verifier || '', params, summary: summary || conditionTitle(id), setupComplete: true }; }
function combinedConditionPatch(draft = {}, item = null, finish = false) { const base = draft.conditions || {}; const items = Array.isArray(base.items) ? base.items.slice() : []; if (item) items.push(item); const operator = base.operator || (base.id === 'any_condition' ? 'any' : 'all'); const condition = { ...base, operator, items, setupComplete: finish, params: { ...(base.params || {}), items } }; const label = operator === 'any' ? 'достаточно выполнить любое условие' : 'нужно выполнить все условия'; return { conditions: condition, conditionSetupStatus: finish ? 'complete' : 'in_progress', conditionSummary: `${label}; условий: ${items.length}` }; }

async function setupCombinedCondition(ctx = {}, current = {}) {
  const d = current.draft || {}; const action = valueFromCtx(ctx, 'combineAction', ['action']); const base = d.conditions || {}; const items = Array.isArray(base.items) ? base.items : [];
  const selectedPostId = valueFromCtx(ctx, 'conditionPostId', ['postId']) || d.postId; const selectedPostTitle = valueFromCtx(ctx, 'conditionPostTitle', ['postTitle']) || d.postTitle; const selectedChannelId = valueFromCtx(ctx, 'conditionChannelId', ['channelId']) || d.channelId; const selectedChannelTitle = valueFromCtx(ctx, 'conditionChannelTitle', ['channelTitle']) || d.channelTitle; const minComments = numberFromCtx(ctx, 'minComments') || 1; const minReactions = numberFromCtx(ctx, 'minReactions') || 1; const keyword = valueFromCtx(ctx, 'keyword', ['phrase']) || 'хочу подарок'; const pollId = valueFromCtx(ctx, 'pollId') || 'выбранный квиз';
  let item = null;
  if (action === 'finish') { if (items.length < 2) return { ok: false, error: 'condition_combined_min_required', flow: current.flow, step: current.step, draft: d, min: 2 }; return next(ctx, combinedConditionPatch(d, null, true)); }
  if (action === 'add_subscription') { if (!selectedChannelId) return { ok: false, error: 'condition_channel_required', flow: current.flow, step: current.step, draft: d }; item = simpleCondition('subscribe_one_channel', { channelId: selectedChannelId, channelTitle: selectedChannelTitle }, `подписан на канал: ${channelTitleOf(selectedChannelTitle, selectedChannelId)}`); }
  else if (action === 'add_comment') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; item = simpleCondition('comment_on_post', { postId: selectedPostId, postTitle: selectedPostTitle, minComments: 1 }, `оставил комментарий под постом: ${postTitleOf(selectedPostTitle, selectedPostId)}`); }
  else if (action === 'add_comment_count') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; item = simpleCondition('comment_count_on_post', { postId: selectedPostId, postTitle: selectedPostTitle, minComments }, `оставил минимум ${minComments} комментариев под постом: ${postTitleOf(selectedPostTitle, selectedPostId)}`); }
  else if (action === 'add_keyword') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; item = simpleCondition('comment_keyword', { postId: selectedPostId, postTitle: selectedPostTitle, keyword, matchMode: 'contains', caseSensitive: false }, `написал “${keyword}” под постом: ${postTitleOf(selectedPostTitle, selectedPostId)}`); }
  else if (action === 'add_reaction') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; item = simpleCondition('reaction_on_post', { postId: selectedPostId, postTitle: selectedPostTitle, reaction: valueFromCtx(ctx, 'reaction') || 'any' }, `поставил реакцию на пост: ${postTitleOf(selectedPostTitle, selectedPostId)}`); }
  else if (action === 'add_reaction_count') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; item = simpleCondition('reaction_count_on_post', { postId: selectedPostId, postTitle: selectedPostTitle, minReactions }, `поставил минимум ${minReactions} реакций на пост: ${postTitleOf(selectedPostTitle, selectedPostId)}`); }
  else if (action === 'add_quiz') { item = simpleCondition('quiz_answer', { pollId }, 'ответил на квиз / опрос'); }
  else { return { ok: false, error: 'condition_combined_action_required', flow: current.flow, step: current.step, draft: d }; }
  return goTo(ctx, 'condition_setup', combinedConditionPatch(d, item, false));
}

async function setupCondition(ctx = {}) {
  const current = await getCurrent(ctx); if (!current.ok) return current; if (current.step?.id !== 'condition_setup') return { ok: false, error: 'unexpected_step', expected: 'condition_setup', actual: current.step?.id || '', flow: current.flow, step: current.step, draft: current.draft };
  const d = current.draft || {}; const id = d.conditions?.id || d.conditionId || d.accessMode;
  if (id === 'all_conditions' || id === 'any_condition') return setupCombinedCondition(ctx, current);
  const samePost = valueFromCtx(ctx, 'conditionPostMode') === 'same_post' || valueFromCtx(ctx, 'useCurrentPost') === '1'; const selectedPostId = valueFromCtx(ctx, 'conditionPostId', ['postId']) || (samePost ? d.postId : ''); const selectedPostTitle = valueFromCtx(ctx, 'conditionPostTitle', ['postTitle']) || (samePost ? d.postTitle : ''); const selectedChannelId = valueFromCtx(ctx, 'conditionChannelId', ['channelId']) || (id === 'subscribe_current_channel' ? d.channelId : ''); const selectedChannelTitle = valueFromCtx(ctx, 'conditionChannelTitle', ['channelTitle']) || (id === 'subscribe_current_channel' ? d.channelTitle : ''); const minComments = numberFromCtx(ctx, 'minComments'); const minReactions = numberFromCtx(ctx, 'minReactions'); const keyword = valueFromCtx(ctx, 'keyword', ['phrase']); const pollId = valueFromCtx(ctx, 'pollId');
  if (id === 'subscribe_current_channel') return next(ctx, completeCondition(d, { params: { channelId: d.channelId, channelTitle: d.channelTitle }, extra: { conditionSummary: `подписан на текущий канал: ${d.channelTitle || 'канал'}` } }));
  if (id === 'subscribe_one_channel') { if (!selectedChannelId) return { ok: false, error: 'condition_channel_required', flow: current.flow, step: current.step, draft: d }; return next(ctx, completeCondition(d, { params: { channelId: selectedChannelId, channelTitle: selectedChannelTitle }, extra: { conditionSummary: `подписан на канал: ${selectedChannelTitle || selectedChannelId}` } })); }
  if (id === 'subscribe_many_channels') { const channelIds = cleanValue(valueFromCtx(ctx, 'channelIds')).split(',').map(cleanValue).filter(Boolean); if (!channelIds.length) return { ok: false, error: 'condition_channels_required', flow: current.flow, step: current.step, draft: d }; return next(ctx, completeCondition(d, { params: { channelIds }, extra: { conditionSummary: `подписан на несколько каналов: ${channelIds.length}` } })); }
  if (id === 'comment_on_post') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; return next(ctx, completeCondition(d, { params: { postId: selectedPostId, postTitle: selectedPostTitle, minComments: 1 }, extra: { conditionSummary: `оставил комментарий под постом: ${selectedPostTitle || selectedPostId}` } })); }
  if (id === 'comment_count_on_post') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; if (!minComments) return { ok: false, error: 'condition_min_comments_required', flow: current.flow, step: current.step, draft: d }; return next(ctx, completeCondition(d, { params: { postId: selectedPostId, postTitle: selectedPostTitle, minComments }, extra: { conditionSummary: `оставил минимум ${minComments} комментариев под постом: ${selectedPostTitle || selectedPostId}` } })); }
  if (id === 'comment_keyword') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; if (!keyword) return { ok: false, error: 'condition_keyword_required', flow: current.flow, step: current.step, draft: d }; return next(ctx, completeCondition(d, { params: { postId: selectedPostId, postTitle: selectedPostTitle, keyword, matchMode: 'contains', caseSensitive: false }, extra: { conditionSummary: `написал фразу “${keyword}” под постом: ${selectedPostTitle || selectedPostId}` } })); }
  if (id === 'reaction_on_post') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; return next(ctx, completeCondition(d, { params: { postId: selectedPostId, postTitle: selectedPostTitle, reaction: valueFromCtx(ctx, 'reaction') || 'any' }, extra: { conditionSummary: `поставил реакцию на пост: ${selectedPostTitle || selectedPostId}` } })); }
  if (id === 'reaction_count_on_post') { if (!selectedPostId) return { ok: false, error: 'condition_post_required', flow: current.flow, step: current.step, draft: d }; if (!minReactions) return { ok: false, error: 'condition_min_reactions_required', flow: current.flow, step: current.step, draft: d }; return next(ctx, completeCondition(d, { params: { postId: selectedPostId, postTitle: selectedPostTitle, minReactions }, extra: { conditionSummary: `поставил минимум ${minReactions} реакций` } })); }
  if (id === 'quiz_answer' || id === 'quiz_correct_answer') { if (!pollId) return { ok: false, error: 'condition_poll_required', flow: current.flow, step: current.step, draft: d }; return next(ctx, completeCondition(d, { params: { pollId, answerId: valueFromCtx(ctx, 'answerId') }, extra: { conditionSummary: id === 'quiz_correct_answer' ? 'ответил правильно на квиз' : 'ответил на квиз / опрос' } })); }
  return next(ctx, completeCondition(d, { params: {}, extra: { conditionSummary: d.accessLabel || 'условие выбрано' } }));
}
function canReviewConditions(draft = {}) { const c = draft.conditions || {}; if (!c.id) return { ok: false, error: 'condition_required' }; if (['all_conditions', 'any_condition'].includes(c.id) && (!Array.isArray(c.items) || c.items.length < 2)) return { ok: false, error: 'condition_combined_min_required', min: 2 }; if (conditionNeedsSetup(c) && draft.conditionSetupStatus !== 'complete') return { ok: false, error: 'condition_setup_required' }; return { ok: true }; }
function titlePatchForFlow(flowId, text) { if (flowId === 'buttons.create') return { title: text, buttonTitle: text, titleInputAt: new Date().toISOString() }; if (flowId === 'lead_magnets.create') return { title: text, leadMagnetTitle: text, titleInputAt: new Date().toISOString() }; return { title: text, titleInputAt: new Date().toISOString() }; }
function urlPatchForFlow(flowId, url) { if (flowId === 'buttons.create') return { buttonUrl: url, url: url, urlInputAt: new Date().toISOString() }; return { url: url, urlInputAt: new Date().toISOString() }; }
function materialPatchForFlow(flowId, text) { const normalized = normalizeUrl(text); const isUrl = isValidHttpUrl(normalized); return { materialType: isUrl ? 'url' : 'text', material: isUrl ? normalized : text, materialPreview: isUrl ? `ссылка: ${cut(normalized, 90)}` : `текст: ${cut(text, 90)}`, materialInputAt: new Date().toISOString() }; }
async function acceptInput(ctx = {}, explicitText = '') {
  const current = await getCurrent(ctx); if (!current.ok) return current; const text = cleanValue(explicitText || textInputFromCtx(ctx)); if (!text) return { ok: false, error: 'text_required', flow: current.flow, step: current.step, draft: current.draft };
  if (current.step?.id === 'input_title') { if (text.length > 64) return { ok: false, error: 'text_too_long', limit: 64, flow: current.flow, step: current.step, draft: current.draft }; return next(ctx, titlePatchForFlow(current.flow.id, text)); }
  if (current.step?.id === 'input_url') { if (current.flow.id !== 'buttons.create') return { ok: false, error: 'url_step_not_supported_for_flow', flow: current.flow, step: current.step, draft: current.draft }; const url = normalizeUrl(text); if (!isValidHttpUrl(url)) return { ok: false, error: 'url_invalid', flow: current.flow, step: current.step, draft: current.draft }; if (url.length > 500) return { ok: false, error: 'url_too_long', limit: 500, flow: current.flow, step: current.step, draft: current.draft }; return next(ctx, urlPatchForFlow(current.flow.id, url)); }
  if (current.step?.id === 'input_material') { if (current.flow.id !== 'lead_magnets.create') return { ok: false, error: 'material_step_not_supported_for_flow', flow: current.flow, step: current.step, draft: current.draft }; if (text.length > 2000) return { ok: false, error: 'material_too_long', limit: 2000, flow: current.flow, step: current.step, draft: current.draft }; const patch = materialPatchForFlow(current.flow.id, text); if (current.draft?.editMode === 'lead_material') return goTo(ctx, 'review_save', patch); return next(ctx, patch); }
  return { ok: false, error: 'unexpected_input_step', expected: 'input_title_input_url_or_input_material', actual: current.step?.id || '', flow: current.flow, step: current.step, draft: current.draft };
}
async function cancel(ctx = {}, reason = 'cancel') { const adminId = adminIdOf(ctx); const session = await stateManager.resetSession(adminId, reason); return { ok: true, session }; }
function selfTest() { const flows = definitions.listFlows(); const defs = definitions.selfTest ? definitions.selfTest() : {}; const catalog = conditionCatalog.selfTest(); const combined = conditionCatalog.find('all_conditions') && conditionCatalog.find('any_condition'); return { ok: flows.length >= 2 && defs.leadMagnetFullFlowReady === true && catalog.ok === true && !!combined, runtimeVersion: RUNTIME, supports: ['selectChannel','selectPostSource','selectPost','capturePost','selectConditionGroup','selectAccess','setupCondition','setupCombinedCondition','canReviewConditions','acceptInput'], guards: ['condition_setup_required','condition_post_required','condition_min_comments_required','condition_keyword_required','condition_poll_required','condition_combined_min_required'], editMaterialSkipsConditionSetup: true, combinedConditionsReady: true, leadMagnetFullFlowReady: true, flows: flows.map((flow) => ({ id: flow.id, section: flow.section, steps: flow.steps.map((s) => s.id) })) }; }
module.exports = { RUNTIME, start, getCurrent, patchDraft, goTo, next, selectChannel, selectPostSource, selectPost, capturePost, selectConditionGroup, selectAccess, setupCondition, canReviewConditions, acceptInput, cancel, selfTest, cleanValue, textInputFromCtx, normalizeUrl, isValidHttpUrl };
