'use strict';

const menuRenderer = require('./menuRenderer');
const conditionCatalog = require('./leadMagnetConditionCatalog');

const RUNTIME = 'ADMINKIT-CORE-FLOW-SCREEN-1.5-CONDITION-SETUP';

function clean(value = '') { return String(value ?? '').replace(/\s+/g, ' ').trim(); }
function cut(value = '', max = 58) { const s = clean(value); return s.length > max ? `${s.slice(0, Math.max(1, max - 1))}…` : s; }
function isHuman(value = '') { const s = clean(value); if (!s) return false; if (/^-?\d{6,}$/.test(s)) return false; if (/^[a-f0-9]{12,}$/i.test(s)) return false; return true; }
function postLabel(draft = {}) { return cut(draft.postTitle || draft.postPreview || draft.title || draft.postText || draft.postId || 'выбранный пост', 60); }
function channelLabel(draft = {}) { const title = draft.channelTitle || draft.channelName || draft.channelDisplayName || ''; if (isHuman(title)) return cut(title, 60); if (draft.channelId) return 'выбранный канал'; return ''; }

function stepHint(flowId, stepId) {
  if (flowId === 'lead_magnets.create') {
    if (stepId === 'select_channel') return 'Сначала выберите канал, для которого создаём лид-магнит. Это нужно, чтобы дальше показать посты именно этого канала.';
    if (stepId === 'select_post_source') return 'Выберите источник поста: взять из базы, переслать новый пост или добавить старый пост, который был до подключения бота.';
    if (stepId === 'select_post') return 'Выберите пост из базы или запустите capture-flow. Если в базе пусто — переслите пост из канала, чтобы Core добавил его в registry.';
    if (stepId === 'input_title') return 'Пост выбран. Теперь введите название лид-магнита: чек-лист, гайд, промокод, подборка.';
    if (stepId === 'input_material') return 'Добавьте материал сообщением: текст, промокод или ссылку. Файл/фото подключаются через material adapter отдельным шагом.';
    if (stepId === 'select_condition_group') return 'Выберите группу условий, чтобы не показывать все сценарии одной длинной простынёй.';
    if (stepId === 'select_access') return 'Выберите конкретное условие получения подарка.';
    if (stepId === 'condition_setup') return 'Теперь нужно заполнить параметры выбранного условия: пост, канал, число комментариев/реакций, ключевую фразу или квиз.';
    if (stepId === 'review_conditions') return 'Проверьте условия получения. К сохранению можно перейти только после настройки обязательных параметров.';
    if (stepId === 'review_save') return 'Проверьте лид-магнит и сохраните. Core запишет его в ak_post_lead_magnets без legacy adapters.';
  }
  if (flowId === 'buttons.create') {
    if (stepId === 'select_post') return 'Выберите пост из базы или запустите capture-flow: переслать новый/старый пост из канала.';
    if (stepId === 'input_title') return 'Пост выбран. Теперь введите понятное название кнопки сообщением.';
    if (stepId === 'input_url') return 'Введите ссылку сообщением. Core принимает только http/https URL и сохранит её в ak_post_buttons.';
    if (stepId === 'review_save') return 'Проверьте название и ссылку. После нажатия “Сохранить” Core запишет кнопку только в ak_post_buttons.';
  }
  return 'Продолжайте сценарий по шагам. Состояние хранится в единой Core-сессии.';
}

function channelButtons(flowId, channels = []) {
  if (!channels.length) return [{ text: '➕ Использовать текущий канал', route: 'flow.select_channel', data: { flowId, channelId: 'current-channel', channelTitle: 'Текущий канал' } }];
  return channels.slice(0, 10).map((channel, index) => ({ text: `${index + 1}. ${cut(channel.channelTitle || channel.title || channel.channelId || 'Канал', 52)}`, route: 'flow.select_channel', data: { flowId, channelId: String(channel.channelId || channel.id || ''), channelTitle: cut(channel.channelTitle || channel.title || 'Канал', 100) } }));
}
function postSourceButtons(flowId) { return [
  { text: '📚 Выбрать пост из базы', route: 'flow.select_post_source', data: { flowId, postSource: 'registry', postSourceLabel: 'выбрать из базы' } },
  { text: '📨 Переслать новый пост', route: 'flow.capture_post', data: { flowId, captureMode: 'forwarded_post' } },
  { text: '🔎 Найти / переслать старый пост', route: 'flow.capture_post', data: { flowId, captureMode: 'old_post' } }
]; }
function postPickerButtons(flowId, posts = []) { const buttons = []; if (posts.length) buttons.push(...posts.slice(0, 8).map((post, index) => ({ text: `${index + 1}. ${cut(post.displayTitle || post.title || post.postTitle || post.postId || post.id || 'Пост', 55)}`, route: 'flow.select_post', data: { flowId, postId: String(post.postId || post.id || post.key || ''), postTitle: cut(post.displayTitle || post.title || post.postTitle || 'Пост', 100), ...(post.channelId ? { channelId: String(post.channelId) } : {}), ...(post.channelTitle ? { channelTitle: cut(post.channelTitle, 100) } : {}) } }))); else buttons.push({ text: 'Выбрать тестовый пост', route: 'flow.select_post', data: { flowId, postId: 'debug-post', postTitle: 'Тестовый пост' } }); buttons.push({ text: '📨 Переслать пост из канала', route: 'flow.capture_post', data: { flowId, captureMode: 'forwarded_post' } }); buttons.push({ text: '🔎 Найти старый пост', route: 'flow.capture_post', data: { flowId, captureMode: 'old_post' } }); return buttons; }
function conditionGroupButtons(flowId) { return [
  { text: '📡 Подписка', route: 'flow.select_condition_group', data: { flowId, conditionGroup: 'subscription', conditionGroupLabel: 'Подписка' } },
  { text: '💬 Комментарии', route: 'flow.select_condition_group', data: { flowId, conditionGroup: 'comments', conditionGroupLabel: 'Комментарии' } },
  { text: '❤️ Реакции', route: 'flow.select_condition_group', data: { flowId, conditionGroup: 'reactions', conditionGroupLabel: 'Реакции' } },
  { text: '🧩 Квизы / опросы', route: 'flow.select_condition_group', data: { flowId, conditionGroup: 'quiz', conditionGroupLabel: 'Квизы / опросы' } },
  { text: '🧱 Комбинированные', route: 'flow.select_condition_group', data: { flowId, conditionGroup: 'combined', conditionGroupLabel: 'Комбинированные' } }
]; }
function accessButtons(flowId = '', group = '') { const all = conditionCatalog.publicButtons().map((item) => ({ ...item, data: { ...(item.data || {}), flowId } })); const map = { subscription: ['subscribe_current_channel','subscribe_one_channel','subscribe_many_channels'], comments: ['comment_on_post','comment_count_on_post','comment_keyword'], reactions: ['reaction_on_post','reaction_count_on_post'], quiz: ['quiz_answer','quiz_correct_answer'], combined: ['all_conditions','any_condition'] }; const ids = map[group] || null; return ids ? all.filter((b) => ids.includes(b.data?.conditionId)) : all; }
function conditionSetupButtons(flowId = '', draft = {}) { const id = draft.conditions?.id || draft.conditionId || ''; const samePost = { text: '📌 Использовать этот же пост', route: 'flow.setup_condition', data: { flowId, conditionPostMode: 'same_post', useCurrentPost: '1', minComments: id === 'comment_count_on_post' ? 1 : '', minReactions: id === 'reaction_count_on_post' ? 1 : '' } }; if (id === 'subscribe_current_channel') return [{ text: '✅ Подтвердить текущий канал', route: 'flow.setup_condition', data: { flowId } }]; if (id === 'subscribe_one_channel') return [{ text: '📡 Использовать текущий канал', route: 'flow.setup_condition', data: { flowId, conditionChannelId: draft.channelId || '', conditionChannelTitle: draft.channelTitle || '' } }]; if (id === 'subscribe_many_channels') return [{ text: '📚 Использовать текущий канал как первый', route: 'flow.setup_condition', data: { flowId, channelIds: draft.channelId || '' } }]; if (id === 'comment_on_post') return [samePost]; if (id === 'comment_count_on_post') return [samePost, { text: '🔢 3 комментария под этим постом', route: 'flow.setup_condition', data: { flowId, conditionPostMode: 'same_post', useCurrentPost: '1', minComments: 3 } }]; if (id === 'comment_keyword') return [{ text: '🔑 Фраза “хочу подарок” под этим постом', route: 'flow.setup_condition', data: { flowId, conditionPostMode: 'same_post', useCurrentPost: '1', keyword: 'хочу подарок' } }]; if (id === 'reaction_on_post') return [samePost]; if (id === 'reaction_count_on_post') return [{ text: '🔥 1 реакция на этом посте', route: 'flow.setup_condition', data: { flowId, conditionPostMode: 'same_post', useCurrentPost: '1', minReactions: 1 } }]; if (id === 'quiz_answer' || id === 'quiz_correct_answer') return [{ text: '🧩 Тестовый квиз', route: 'flow.setup_condition', data: { flowId, pollId: 'debug-poll', answerId: id === 'quiz_correct_answer' ? 'debug-answer' : '' } }]; return [{ text: '✅ Подтвердить условие', route: 'flow.setup_condition', data: { flowId } }]; }
function draftSummary(flowId = '', draft = {}) { const lines = []; const c = channelLabel(draft); if (c) lines.push(`Канал: ${c}`); if (draft.postSourceLabel) lines.push(`Источник поста: ${draft.postSourceLabel}`); if (draft.postId || draft.postTitle) lines.push(`Пост: ${postLabel(draft)}`); if (draft.leadMagnetTitle) lines.push(`Название лид-магнита: ${draft.leadMagnetTitle}`); if (draft.materialPreview) lines.push(`Материал: ${draft.materialPreview}`); if (draft.conditionGroupLabel) lines.push(`Группа условий: ${draft.conditionGroupLabel}`); if (draft.accessLabel) lines.push(`Условие: ${draft.accessLabel}`); if (draft.conditionSummary) lines.push(`Параметры: ${draft.conditionSummary}`); if (draft.conditionVerifier) lines.push(`Проверка: ${draft.conditionVerifier}`); if (flowId === 'buttons.create' && draft.buttonTitle) lines.push(`Название кнопки: ${draft.buttonTitle}`); if (flowId === 'buttons.create' && draft.buttonUrl) lines.push(`Ссылка кнопки: ${draft.buttonUrl}`); return lines; }
function renderFlowState(result = {}, options = {}) { const flow = result.flow || {}; const step = result.step || {}; const draft = result.draft || {}; const title = `${options.icon || ''} ${flow.title || 'Сценарий'} — ${step.title || 'шаг'}`.trim(); const body = [stepHint(flow.id, step.id), '', `Flow: ${flow.id || 'unknown'}`, `Step: ${step.id || 'unknown'}`, ...draftSummary(flow.id, draft)]; const buttons = []; if (step.id === 'select_channel') buttons.push(...channelButtons(flow.id, options.channels || [])); if (step.id === 'select_post_source') buttons.push(...postSourceButtons(flow.id)); if (step.id === 'select_post') buttons.push(...postPickerButtons(flow.id, options.posts || [])); if (step.id === 'select_condition_group') buttons.push(...conditionGroupButtons(flow.id)); if (step.id === 'select_access') buttons.push(...accessButtons(flow.id, draft.conditionGroup)); if (step.id === 'condition_setup') buttons.push(...conditionSetupButtons(flow.id, draft)); if (step.id === 'review_conditions') buttons.push({ text: '➡️ Перейти к сохранению', route: 'flow.next', data: { flowId: flow.id || '' } }); if (step.id === 'review_save') buttons.push({ text: '✅ Сохранить в Core', route: 'flow.save', data: { flowId: flow.id || '' } }); if (options.backRoute) buttons.push({ text: '↩️ Назад к разделу', route: options.backRoute }); buttons.push({ text: '✖️ Отменить сценарий', route: 'flow.cancel', data: { flowId: flow.id || '' } }); return menuRenderer.renderScreen({ title, body, buttons, homeRoute: 'main.home' }); }
function selfTest() { const catalog = conditionCatalog.selfTest(); return { ok: true, runtimeVersion: RUNTIME, saveActionReady: true, humanPostLabelReady: true, humanChannelLabelReady: true, selectChannelScreenReady: true, selectPostSourceScreenReady: true, conditionGroupScreenReady: true, conditionSetupScreenReady: true, leadMagnetAccessButtonsReady: true, leadConditionCatalogReady: catalog.ok === true, leadConditionCount: catalog.count, postCaptureButtonsReady: true, reviewConditionsNextReady: true }; }
module.exports = { RUNTIME, renderFlowState, stepHint, postPickerButtons, accessButtons, draftSummary, selfTest, postLabel, channelLabel };
